### ISSUE TITLE
Minimum files for compare

### ISSUE THREAD

**Issue by kirkgrubbs1** [MrOlm/inStrain#100]
Hello,
     I have produced a few hundred profiles using inStrain compare. These have a tendency to get quite large, and require lots of time to move around, archive, compress, extract,....etc. I was wondering if there is a list of the minimum files from the profiles needed to run compare?

**Comment by kirkgrubbs1** [comment]
After process of elimination, the following files were the only ones needed to still run successfully:

attributes.tsv  covT.hd5  cumulative_snv_table.csv.gz  scaffold2length.json

**Comment by MrOlm** [comment]
Sorry that by the time it took me to respond you've figured this out on your own! Let me know if you have any other questions

**Comment by kirkgrubbs1** [comment]
no worries, good to know i didn't miss something
