### ISSUE TITLE
null model seems not being consistently applied leading to wrong allelle_counts

### ISSUE THREAD

**Issue by zhaoc1** [MrOlm/inStrain#102]
Hi,

Thanks for providing the Null Model such that "the number of reads for the variant bases must be higher than a null model given the coverage of the base". I ran Instrain with the default parameters for the mock sample in the Instrain paper (SRR12324251), and I noticed sometimes the null model was not applied as intended (as far as to my understanding).

Take the `Salmonella_enterica_chromosome` as an example. I added the min_variant_base_read_count to the output of `instrain profile`:
 
![image](https://user-images.githubusercontent.com/9036669/159141749-cb2f0401-22f6-4460-ab6e-3c88ef083e4a.png)

As we can see, the read counts of the above listed variant bases are not "higher than the null model", yet they are still counted as a valid variant site, and cause wrong `allele_count`. 

It would also be that I mis-understood of the application of the null model. Would love to hear some insights!

Thank you,
Chunyu

**Comment by MrOlm** [comment]
Thank you for reaching out and I appreciate the detailed bug report. Just based on this output I think "cryptic" SNVs are at the heart of this problem. 

Cryptic SNVs are SNVs that ARE counted as SNVs when dealing with stringently mapped reads, but ARE NOT counted as SNVs when dealing with the all reads. For almost everything inStrain does cryptic SNVs are ignored, and in response to this issue, I may very will filter out cryptic SNVs from this output file to prevent further confusion. In this example it looks like all wrongly reported SNVs are cryptic (column cryptic = True). For the top SNV, for example, it could be that case that in filtering reads to 99% ANI you detect 3 "C" and 3 "T" bases. At this point the null model would call a SNV. At the full read stringency level, the 3 "C"s no longer count as a SNV, and thus the SNV is counted as "cryptic" and ignored by most all aspects of inStrain. For more details on why inStrain detects cryptic SNVs at all, see here https://instrain.readthedocs.io/en/latest/advanced_use.html#dealing-with-mm 

There are two ways to deal with this- 1) filter out and ignore cryptic SNVs, or 2) run inStrain with `--database_mode` or with `--skip_mm_level` (this will render inStrain unable to detect cryptic SNVs in the first place)

I know this is confusing and I apologize that this isn't more clear from the documentation. Please let me know if you have any other questions of if these suggestions don't solve your problem. In the next inStrain update I'll remove cryptic SNVs from this output file to avoid further confusion.

Best,
MO

**Comment by zhaoc1** [comment]
Thanks for the quick reply! I didn't pay much attention to the "cryptic" column. 

To make sure I understand the "cryptic" SNVs correctly, I have a couple questions after reading the `dealing-with-mm` page.
1. "stringently mapped reads": refer to perfectly mapped reads (mm ==0)?
2. "all reads":  reads passing the InStrain post-alignment filter?

Back to my example, position 2622664 and 2622674: those two SNVs are not "cryptic" sites. However, the 2nd allele (A:4, and A:3) are equal to the null model minimal read counts, instead of higher. Therefore, those two sites are bi-allelic sites (?).

**Comment by MrOlm** [comment]
1) In this case, "stringently mapped reads" are reads with any level of mismatch less than the maximum limit

2) Yes exactly

2622664 is bi-allelic (2 bases have >= the minimum required) and 2622674 is tri-allelic (3 bases have >= the minimum required)

**Comment by zhaoc1** [comment]
1-2. Okay. I understand now. The post-alignment filter include two separate parts: (1) READ FILTERING OPTIONS - "all reads" (2) READ ANI OPTIONS, which define the maximum limit of the mm -- "stringently mapped reads". And for the `instrain profile` output, we as users should really filter out `cryptic == TRUE` and only consider `cryptic == FALSE` sites.

As for the above mentioned two sites: I thought `higher than` null model doesn't include the minimal boundary, and it seems like it is " >=" instead of ">". 

Thanks again for the instant reply! Very much appreciate it!

Chunyu

**Comment by MrOlm** [comment]
Yes that's exactly right. Sorry this wasn't more clear from the online documentation and thanks for reaching out. Let me know if you run into any more snags.

-MO
