### ISSUE TITLE
The question for running command "inStrain profile"

### ISSUE THREAD

**Issue by toggle0511** [MrOlm/inStrain#103]
Hi,

I'm using command "inStrain profile" for for long-read (nanopore) sequencing data, and material is single genome(.fasta file) and bam file(~500MB) is from minimap2 (The alignment option is  "map-ont " and "--sam-hit-only"). It spends about 1 hour in Step 2. and then stopped,but I don't know why.

The command I tried:
>  inStrain profile 7839_onlymapping.bam ../ref/LT2.fasta --use_full_fasta_header -o 7839_instrain

The result is as follows：

```
**************************************************
.:: inStrain profile Step 2. Profile scaffolds ::..
**************************************************


Profiling splits: 100%|██████████| 7/7 [02:00<00:00, 17.21s/it]
Merging splits and profiling genes:   0%|          | 0/1 [00:00<?, ?it/s]/home/yuqing109/miniconda2/envs/instrain/lib/python3.8/site-packages/inStrain/profile/profile_utilities.py:522: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  counts = pd.Series(index=np.arange(fill_zeros))
/home/yuqing109/miniconda2/envs/instrain/lib/python3.8/site-packages/inStrain/profile/profile_utilities.py:522: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  counts = pd.Series(index=np.arange(fill_zeros))
```
The log is as follows：

[log.log](https://github.com/MrOlm/inStrain/files/8357306/log.log)

Sorry for the basic question!

Thank you!!
Nick

**Comment by MrOlm** [comment]
Hmm... a couple of things could be going on. 1) The program could be running out of RAM, which causes it to crash, or 2) the program couple be having trouble establishing processes on your system for some reason.

Could you try again with the option `-p 1`? That should both reduce RAM usage and skip the establishment of additional processes.

Thanks,
MO

**Comment by toggle0511** [comment]
Thank you for reply!!

I have tried the command `-p 1 `, it still spends over two hours. And then I check my system which has about 500g of RAM.
However I coud run the test data for `inStrain profile` successfully. I have no idea why my data can't run. 

If you need data, please tell your e-mail.I will send it to you.

Thanks,
Nick

**Comment by MrOlm** [comment]
Hi Nick- that would be great. Email is mattolm@stanford.edu

**Comment by toggle0511** [comment]
I have sent Email to you.
Thank you for your help!
