### ISSUE TITLE
Issue of "I dont know how to process ... (the gene file)"

### ISSUE THREAD

**Issue by ChaoLab** [MrOlm/inStrain#106]
Hi @MrOlm,
When I was running a bam file, with reference fasta, and its prodigal annotated genes, I encountered this issue (Line 27 in the attached log file). I used prodigal with the "-p meta" option. I am wondering what's the reason for this error?

[04.run_inStrain.for_test.log](https://github.com/MrOlm/inStrain/files/8849793/04.run_inStrain.for_test.log)

**Comment by MrOlm** [comment]
Hello,

hmm- that flag shouldn’t be a problem with prodigal. Could you post what the first lines of genes file looks like?

-Matt

**Comment by ChaoLab** [comment]
It is like this:

[All_phage_species_rep_gn_containing_AMG.fasta.genes.fasta.header_n_200.txt](https://github.com/MrOlm/inStrain/files/8850107/All_phage_species_rep_gn_containing_AMG.fasta.genes.fasta.header_n_200.txt)

**Comment by ChaoLab** [comment]
Hi @MrOlm, Many thanks for your reply. After I changed the file extension, I can run it through. While, I got this error report then and the process has been hanging on there for a very long time without any real computing being running so I have to kill it. I attach the log file here


[04.run_inStrain.using_TYMEFLIES_bam.log](https://github.com/MrOlm/inStrain/files/8869141/04.run_inStrain.using_TYMEFLIES_bam.log)

**Comment by MrOlm** [comment]
Hello,

OK- I see in the log file that inStrain is giving a lot of errors. It seems like it could be related to the .fasta file. Can you confirm:

1) The .fasta file you're giving inStrain is THE SAME .fasta file you used for metagenomic mapping to generate the .bam file?

2) You're using the most up-to-date version of inStrain?

-MO
