### ISSUE TITLE
Question: SNVs shared across samples

### ISSUE THREAD

**Issue by cifuj** [MrOlm/inStrain#108]
Hi @MrOlm, 

I have been using inStrain to characterise the population-level diversity on a bin across multiple samples. 
The bin is present in multiple samples (cov. breadth >80% and cov. >50x), and I would like to compare the nucleotide diversity (π), SNP/kbp, ∂N/∂S. 
If I understand correctly, I could compare π as it is related to all genome positions in the bin, and I can filter the ∂N/∂S values for the genes that are present in the samples. 
However, in my case the number of population divergent sites vary from sample to sample. 
Is there anyway to obtain the population divergent sites that are shared across all the samples? 

Thank you in advance!
Jerónimo

**Comment by MrOlm** [comment]
Hi Jerónimo,

Yes, there are a couple of ways of doing this.

1) If you use `inStrain compare` with the `--store_mismatch_locations`, inStrain will create the file `pairwise_SNP_locations.tsv` (https://instrain.readthedocs.io/en/latest/example_output.html#pairwise-snp-locations-tsv). This file compares SNVs at positions that are covered by at least 5 reads in both samples

2) If you provide the locations of the `.bam` files to `inStrain compare`, you can generate a series of files that list the full frequency table for each position (https://instrain.readthedocs.io/en/latest/example_output.html#pooled-snv-info-tsv-pooled-snv-data-tsv-and-pooled-snv-data-keys-tsv)

Hope this is what you're looking for any let me know if you have any questions!
-Matt
