### ISSUE TITLE
Question about non-synonymous/synonymous mutation calculations when gene is on the negative strand

### ISSUE THREAD

**Issue by szimmerman92** [MrOlm/inStrain#112]
Hi @MrOlm,

Sorry to open another issue, but I am a little confused about how the SNV reporting from the inStrain profile command output works when the gene is on the negative strand.

Below is a line from my SNVs.tsv file

scaffold	position	position_coverage	allele_count	ref_base	con_base	var_base	ref_freq	con_freq	var_freq	A	C	T	G	gene	mutation	mutation_type	cryptic	class
MGG17661_137	4	5	2	**G	A**	C	0.0	0.4	0.4	2	2	1	0	MGG17661_137_1	**N:T4I**	N	False	pop_SNV

The important things to note are in bold. According to this output, this mutation results in a change from the amino acid T to the amino acid I. 

According to my codon table, the only way you can get from a Threonine to an Isoleucine is by mutating a C to a T(U) which is inconsistent with the output above, which says the mutation is from a G to an A. I noticed that the gene referenced here, MGG17661_137_1 is on the negative strand. Below is the full sequence of the gene. Could you please explain how the mutation is calculated? Is this a potential bug?

Thanks so much.

Best,
Sam

>MGG17661_137_1 # 1 # 1482 # -1 # ID=138_1;partial=10;start_type=ATG;rbs_motif=GGA/GAG/AGG;rbs_spacer=5-10bp;gc_cont=0.291
ATGGATGAAAGTTTTTTAAAAAGCCTTAATGTATTATATGTAGAAGATGAAGTTGATATTATTCAGCTTG
TTGAGAAAAGATTTGCACCAAAGTTTAATCAGTTTTTATCTGTAACTTCTGCAGAAGAAGCATTAGAAAT
ATTTAAGCAAAATAGTAATTTTGATTTAATCTTGACAGACTATCTTTTGCCAGGACTTAATGGTATTGAG
TTTGCTAGAAAAATACTGCAAATAAAATCAAAAGTGCCATTCATATTAATTACCGGCTATGTGGATATGC
AGTTTCTTATTGAAGCAATTAATGTAGGTATTACTCAATTTGTATCTAAACCAATACAGTTTAAACTTCT
TAGAAATGCTATAAATAATACTGTAGAATCTGTTGTATTAGAGCATCTGCTTAATAAAAGCAGAGAGAAG
GAATTAGAGCTTTTAAAATATAAAGATATGTATAACACTATACAGCATGATGCAACATTAAGAAAAGAGC
TGCATATTATGCGTAATGATATGTTTAAAAAGTATTTTCATGATGGGGATAATCCTGTTACTTATAACGG
TTGGCAGGTAGAAGTTTTTTATAAAAGTTTGGATATTGTAAGCGGCGATACTTATACATGCAGAACTCTT
GATAATGGCAATGTAGTTATATTTATTGCAGATGCTATGGGAAAAGGTGTTTCTGCTGCTATTACATCAT
TAGTATCTGTTTCGCTTACTAACTATATAATAAAGCAGCATGACAGCAATAAATGTATTTCTAGTGAAGA
AGAAATCAGGTTTATTGCGGAGCAGTGTGTATCTTTTATGCGGGAAAATCTTGTAGAAGATGAAGTATTA
TGTGCAATATTTGCTTATTTTGATTTTAAAGAAAATAAACTTCAATATGCATCATTTTCAATGCCACGAA
TTCTTCTTCAAACAACAACAGGCAGCATAGAAAAATTACCATCTAATAACCTGCCAATTATGCCTTATGT
TGTTGATATTGCTATTGATTCTGTTGATTTATCAAATGTTTCAAAAGTTGCATTATTTACAGACGGCATT
GTAGAATCAGAAACAAAAGATGGTGTATTATACTCTGCTTACTTAAATGAAAATTTTTCACAGTCACCAT
TTCTTAAATCTTTTTTCAATAATGCTTATACTTATTTAGATGATTTTTATGATGATGTAACTTTATTTTT
TATTAGACGACCATTTACAAATATAATAAAAGAAAAAGTTTATTATTTCCCTACAAAGTATGATAAACTT
GATGAGGCATCAGAAACTATTCGTCAGGAAATGGTTGACTGCGGTATAGATGTAGATAGACATGATTCAT
TTTTTACAGCACTGTCTGAATGTATTATGAATGCTTATGAACATGGAAATCTTGCAATTACATTTGCTAT
TAAGCATGAATTAATAAAAAATGGCGATTATGAAGAAGAACTCTTGAAAAAAGAAAAAAATAATGATAAG
ATGATAACTATC

**Comment by MrOlm** [comment]
Hi Sam,

1) I just merged your pull request- thanks again!

2) A mutation of G to A in the context of the DNA .fasta file should correspond to a mutation of C to T in the context of the negative strand gene, yes? All variants in the SNVs.tsv file are in the context of the .fasta file, not the context of the gene file

Best,
Matt

**Comment by szimmerman92** [comment]
Hi Matt,

Thanks for the quick response. I understand now. I was able to make a script that would report whether the SNPs reported in the inStrain compare results (when using store_mismatch_locations) are synonymous or non-synonymous. Not quite production ready yet, but would that be of any interest to you?

Thanks again!

Best,
Sam

**Comment by MrOlm** [comment]
Hi Sam,

Yeah that would be great! Feel free to email me non-production-ready code (mattolm@stanford.edu) and I can implement myself in the next update.

Thanks again,
Matt
