### ISSUE TITLE
Use bining data as ref-genome

### ISSUE THREAD

**Issue by BaylorLyu** [MrOlm/inStrain#118]
Thanks for you remarkable work. I use inStrain to analyze SNV，but i found that too much mutation are classified to SNS. So i want to use my data after bining as ref-database, is that feasible for mutation analyze？

**Comment by MrOlm** [comment]
Yes, that's totally feasible! You can also merge binned data with a database if you're prefer, as described here: https://instrain.readthedocs.io/en/latest/tutorial.html#tutorial-3-merging-custom-genomes-with-an-existing-genome-database

Best,
Matt

**Comment by BaylorLyu** [comment]
Thanks for you reply，you answer help me a lot.

**Comment by BaylorLyu** [comment]
I use bining result as my database. And there is new error

ERROR:root:read filtering whole scaffold exception- s__Pseudobutyricicoccus_sp003477405_15370_length_3048_cov_3.729369
ERROR:root:read filtering whole scaffold exception- s__Ruminococcus_C_callidus_10550_length_4542_cov_13.173836
[E::bgzf_read_block] Invalid BGZF header at offset 996176391
[E::bgzf_read] Read block operation failed with error 3 after 0 of 4 bytes
truncated file
Traceback (most recent call last):
  File "/home/lbl/miniconda3/envs/instrain/lib/python3.8/site-packages/inStrain/filter_reads.py", line 860, in scaffold_profile_wrapper
    pair2info, cur_log = get_paired_reads(bam_init, scaff)
  File "/home/lbl/miniconda3/envs/instrain/lib/python3.8/site-packages/inStrain/filter_reads.py", line 897, in get_paired_reads
    for read in iter:
  File "pysam/libcalignmentfile.pyx", line 2108, in pysam.libcalignmentfile.IteratorRowRegion.__next__
OSError: truncated file

How to fix it?  i am sure i use the right step for database build.
