### ISSUE TITLE
GenomeWide compare failed

### ISSUE THREAD

**Issue by elizabethmcd** [MrOlm/inStrain#12]
I ran the profile workflow with `inStrain profile 2013-05-13-EBPR-mapping.sam ../bins/R1R2-EBPR-combined-bins.fasta -o 2013-05-13-profiling` using version 1.2.7 of inStrain, and installed with pip. I got past profiling the reads/scaffolds, but got this error at the GenomeWide comparison step: 

```
03-25 15:29 DEBUG    Done processing scaffolds- making SNV profile
03-25 16:01 INFO     Storing output
03-25 16:01 DEBUG    Writing output files now
03-25 16:02 INFO     ***************************************************
  .:: inStrain profile Step 3. Profile genes ::..
***************************************************

03-25 16:02 INFO     Nevermind! You didnt include a genes file
03-25 16:02 INFO     ***************************************************
.:: inStrain profile Step 4. Make genome-wide ::..
***************************************************

03-25 16:02 DEBUG    Loading scaffold to bin
03-25 16:02 INFO     Scaffold to bin will consider all scaffolds the same genome
03-25 16:02 DEBUG    GenomeWide compare failed
Traceback (most recent call last):
  File "/home/GLBRCORG/emcdaniel/.conda/envs/pipenv/lib/python3.8/site-packages/inStrain/genomeUtilities.py", line 508, in main
    gdb = genomeWideFromIS(IS, 'read_compaer', mm_level=mm_level)
  File "/home/GLBRCORG/emcdaniel/.conda/envs/pipenv/lib/python3.8/site-packages/inStrain/genomeUtilities.py", line 92, in genomeWideFromIS
    gdb = _add_stb(db, stb)
  File "/home/GLBRCORG/emcdaniel/.conda/envs/pipenv/lib/python3.8/site-packages/inStrain/genomeUtilities.py", line 130, in _add_stb
    gdb = db.copy()
AttributeError: 'NoneType' object has no attribute 'copy'
```

There are no output or figures files, as this step failed.

**Comment by elizabethmcd** [comment]
Ok, just read a couple of other issues and realized to make GenomeWide compare work, it has to be done with multiple samples mapped to the same reference index. I'll try that.

**Comment by elizabethmcd** [comment]
An update on this issue. I ran the profile workflow as above just with 2 genomes instead of the full set of ~70 that I was before. I have the same error in my log file as is described above, but it looks like all the figures, output, and raw data are there. Whereas before I didn't have anything at the end.

**Comment by MrOlm** [comment]
Hello,

OK, so this is dumb and confusing (and will be fixed), but that error that you're seeing in the log is supposed to be there when running `profile`. It's trying to treat your profile as a `compare` object and failing to do so (as it should), and it should then proceed normally. The fact that you don't have `GenomeWide scaffold info failed` and `GenomeWide read report failed` in the log means that those operations worked to create the files `genomeWide_scaffold_info.tsv` and `genomeWide_read_report.tsv`.

If it failed to create output, the failure (and appropriate error trace-back) are elsewhere.

Best,
Matt

**Comment by elizabethmcd** [comment]
Ok. Things tend to go smoother (and faster) when I split each genome into a separate job, or do a couple at a time, so things seem to be working that way. I haven't tried to figure out the problem from when I ran ~70 genomes because splitting them up works much better. Thanks!
