### ISSUE TITLE
instrain profile flag "min_read_ani" not working?

### ISSUE THREAD

**Issue by mcmahon-uw** [MrOlm/inStrain#124]
Hi!  I'm trying to adjust the min_read_ani using the flag and it doesn't seem to be having any effect on the output.  I tried using 0.97, 0.99, and 0.9999 and got the same coverage and pi values for my MAG when mapping a metagenome.   When I look in the mapping_info output file, the heading looks like this: 

`# min_read_ani:0.92 max_insert_relative:3 min_insert:50 min_mapq:-1 pairing_filter:all_reads` which makes it look hard-coded to be 92%?  

Here is an example command I used:  

`inStrain profile --pairing_filter all_reads rr0845_sub-vs-MAGv2_3300020483-bin.4.sorted.bam ~/TYMEFLIES/analysis/7_specific_taxa/fastas/MAGv2_3300020483-bin.4.filtered.fna -o ~/TYMEFLIES/analysis/3_instrain/rr0845_sub-vs-MAGv2_3300020483-bin.4_99_IS -p 16 -s MAGv2_3300020483-bin.4.stb --min_read_ani 0.99 --database_mode`

**Comment by MrOlm** [comment]
Hi @mcmahon-uw ,

Thanks for reaching out and apologies for the confusion.

The `--database_mode` flag explicitly sets the following:

```
args.min_read_ani = 0.92
args.skip_mm_profiling = True
args.min_genome_coverage = 1
```

So by removing `--database_mode` and replacing it with `--skip_mm_profiling --min_genome_coverage 1` you should get your intended result.

Best,
Matt

**Comment by mcmahon-uw** [comment]
Oh wow, thanks!!!
