### ISSUE TITLE
The parameter --skip_mm_profiling has an impact in the accurary of the variant calling step?

### ISSUE THREAD

**Issue by gabrieleghiotto** [MrOlm/inStrain#126]
Good evening,
so I am using inStrain profile on anaerobic digestion data and I am choosing how to set the parameters. Since I have almost 350 samples to analyze (7-8M reads each) I was looking to have some suggestion, especially regarding the parameter  --skip_mm_profiling. In the documentation it is written that it saves ram and time, but it does not specify at what cost. If you have any suggestion they will be precious. At the moment I am using --min_read_ani 0.98 --min_mapq 2 --skip_plot_generation, besides all the input files. Moreover, we spoke roughly a couple of months ago about some problems that I observed when launching the software on mock communities. Your suggestion to use and ANI of 0.98 was a great idea. If you are interested I may have a couple of suggestions that you and your team could implement to further improve the accuracy of the variant calling step. 

Kind regards.
Gabriele Ghiotto

**Comment by MrOlm** [comment]
Hi Gabriele,

There's really no cost at all unless you're using the `raw_data` files. The only thing I could suggest is adding a minimum genome coverage threshold (maybe of 1 or so). This saves a lot of time if you're mapping to a large genome database. I would also love to hear any suggestions you have about variant calling!

Thanks,
Matt

**Comment by gabrieleghiotto** [comment]
Thank you for the feedback. Do you think that if I set the minimum genome
coverage to 5 is too much? Then, what do you exactly mean for raw_data
files. My data consist of Illumina reads treated with trimmomatic and then
aligned with bowtie2 to a panel of more than 400 MAGs. The for the
suggestion tomorrow I will meet with my phd supervisor and I will let you
know since he will probably like to participate and give also his input.
Thanks again.

Il giorno gio 29 dic 2022 alle ore 23:05 Matt Olm ***@***.***>
ha scritto:

**Comment by MrOlm** [comment]
I think setting the minimum coverage to 1 vs 5 will likely have very similar runtimes, so I personally would keep it at 1, but it's a personal preference thing.

There is a folder created called `raw_data` that is impacted by the flag, but none of the files in the regular output folder are impacted.

Best,
Matt

**Comment by gabrieleghiotto** [comment]
Thank you again. I will follow your suggestion to keep it at 1 and I will
also use the --skip_mm_profiling, since The data that I will use are the
tabular files of the output folder. I will let you know as soon as possible.

Kind regards.
Gabriele Ghiotto

Il giorno ven 30 dic 2022 alle ore 00:01 Matt Olm ***@***.***>
ha scritto:

**Comment by gabrieleghiotto** [comment]
Goodmorning,
as promised I am here to suggest some aspect to tweak.
1- coverage of the variant is important but not as much as I thought. In
the figure I filtered the variants based on the column position_coverage of
the SNVs_info.tsv file.
2- Position of the SNVs on the scaffold is important: you cannot trust the
variants called at the beginning or the end of the scaffolds, where the
coverage is much lower than the average scaffold coverage. In my analysis I
filtered out all variants on the first and last 250 bp of the scaffolds.
3- Discard all the variants with position_coverage that shift drastically
from the average coverage of the scaffold on which is called. I use a
difference of max [-50;+50] in my analysis but probably it would be better
to set a variable threshold, depending on the length of the scaffolds:
4- ANI differences:
ANI 0.92 (database_mode): 791 SNVs
ANI 0.95 (default): 665 (-16%)
ANI 0.98: 173 (-78%)
ANI 0.99: 66 (-92%)


This is it and if you have any question I am happy to discuss about them.
Now I have another question: at the moment I am investigating some
interesting variants and create the 3D model with Alpha Fold; however, I
bumped into the following issue. Say that I want to study the following
protein predicted with "prodigalv2.6.3".

 >metabat1.133__5875_pilon_220 # 226330 # 229557 # 1 #
ID=2_220;partial=00;start_type=TTG;rbs_motif=AGGAGG;rbs_spacer=5-10bp;gc_cont=0.453
MERNIRVLLDGREVYGFSGQTILDLCTECGVEIPHLCYDPRLSIHGGCSLCMVEVKGAKT
LLRACSNKIFHGMEIYTDSERVKDARKATLELLLSNHVGDCRPPCTLACPARGDVQGYVN
LAAVGLYKEALDLLHENITLPASIGRICPAPCQEECRRNFVDEEPVSIREIKRFISDWGL
EKDMVGHVDEIQENGHSVAIVGGGPAGLSAAFFLRKKGYEVTIFEKESELGGMMRFGIPE
YRLPRHILKKEIEWLLSWGIKTKTNTALGKDITLEQLRIKHDALLLAFGCWQSTPLRVPG
ENLNGVLAGIEFLYDVNNHLPVEIGKKVIVIGGGNTAMDACRCAKRLGAETVTVVYRRTR
QEMPAEDEEIEEAMEEGINFIYLAAPKEIKGHDRVQQLVCEKMVLGEPDASGRRRPIPTG
ETFTIEADTVIAAIGQSPVLHMLPSTIHNGRWILTDENYATPLEKVFACGDLRTGPDIAI
AAIGEGHFAAESIHHYITQGYPKRPYECDVVRDDLGPEDFEDEERQPREVPYVLPASERL
ASPFKEFNKGLTEEQVKKDSKRCMECGCPDIFECKLRAYSVQHEASPNQFSGEKLERFEE
KLKYYDRDMNKCILCGRCVRTCDEIVGLYAIDYVNRGYFTTIQGAYLKPLDESECTGCGV
CVDLCPVGALTEKRKERWPHSEVPIKTQTTCGECSLGCEIYVNSDKTRHNVVRVTTDSGS
PTSPTHGLCCFKGRTFHLNTNRLEIANDSMDRLKKLSGFLRSKERTSIFVGNSLSNEEYE
AIKDTLDLIAPNAIVSVKEVDDFRTFLAQANDKGLKRGTLGQLYEADVAFVIDDNLDEDL
PLISSMLRKRVREGDLKVIYSGSTPGLLDKGSTILLKTNAVELAPLFDALSGTGLIQSAS
KFTGINEENIVLAKNTLAAAKRPITLVGPKVASSTTSSLALINLCIKLDECLYLPLYRGA
NTEGALRILGDLLTPAIDNMSMIKEGKTTQLLAIEPDQSTIELIRSVNGVIKCALLTSKA
HGDINTDIVVPITGWHERYGHVTNLSGSILEQNKTVLPPKELNTLSGLLKILGEL*

From instrain I want to investigate these 2 variants, identified by the
colum id where it is present the scaffold " metabat1.133__5875_pilon", an
"_" and the position of the SNV " 227425". The length of the amino-acidic
sequence for the gene metabat1.133__5875_pilon_220 is 1092 aa, but the
mutation of the amino-acid are reported in position 1096 and 1594. My
question is: this is an error of the software or the position indicated is
the one of the nucleotidic sequence (DNA), because if that is the case then
I am ok, because the length of the gene is 3227 bp. Moreover, I will need
to look at the triplet of nucleotides in position 1096-1097-108 and
15954-1595-1596 so see the aa coded and retrieve the real position along
the peptide.

id KEGG_ko mutation d_Grantham gene start end length aa_seq
metabat1.133__5875_pilon_227425 K00123 E1096V 121
metabat1.133__5875_pilon_220 226330 229557 3227 1092
metabat1.133__5875_pilon_227923 K00123 Y1594C 194
metabat1.133__5875_pilon_220 226330 229557 3227 1092


Il giorno ven 30 dic 2022 alle ore 08:20 Gabriele Ghiotto <
***@***.***> ha scritto:

**Comment by MrOlm** [comment]
Hi Gabriele,

Thank you for your information on SNV calling! That is interesting indeed and thank you for sharing. I will use this info as I improve inStrain SNV calling.

As for your question- if you look at the `mutation` column in the SNVs table, it will let you know the amino acid position of the mutation in the gene.

Best,
Matt
