### ISSUE TITLE
Compare does not create plot 10

### ISSUE THREAD

**Issue by marotbone** [MrOlm/inStrain#128]
Hi there,

First I would like to thank you for the great tool and the nice documentation.

I analyzed 18 bam files successfully and for each the plots are created.
I used the following command for each sample:
`inStrain profile ${bam} ${genome} -o results/IS_${name} -g ${genes_file} -p 32 -c ${min_depth}`
[profile.log](https://github.com/MrOlm/inStrain/files/10465482/profile.log)

Now if I run:
`inStrain compare -i ${paths_to_profile_folders} -bams ${paths_to_bam_files_used_in_profile} -o ${output_path} -p 8 -c 200`

I see the following lines in the log file:
23-01-18 16:46:56 ERROR    This IS object does not have an .stb file; cant use it to make plots
23-01-18 16:46:56 INFO     making plots 10
23-01-18 16:46:56 ERROR    Skipping plot 10 - you don't have all required information. You need to run inStrain genome_wide first
[compare.log](https://github.com/MrOlm/inStrain/files/10465481/compare.log)

My final goal is to create plot 10 for all 18 bam files.
What am I doing wrong?

I attached a log file for the profile and compare command I used.

Thank you in advance.

Best,
Maro

**Comment by MrOlm** [comment]
Hi Maro,

Just to confirm, you're mapping to a single genome? InStrain wants you to have a scaffold to bin file, but that's not really relevant if you're mapping to a single genome.

-Matt

**Comment by marotbone** [comment]
Hi Matt

Yes, it's just one genome.

Best,
Maro

Matt Olm ***@***.***> schrieb am Fr., 20. Jan. 2023, 17:32:

**Comment by MrOlm** [comment]
OK- this should work and there seems to be a bug preventing at the moment. Apologies.

While I work on a fix, a workaround you can do is just create and pass in a .stb file for just your single genome. It's just a file listing which genome all scaffolds belong to (for you, all the same genome).

See here for more info: https://instrain.readthedocs.io/en/latest/overview.html#term-scaffold-to-bin-file

-Matt

**Comment by marotbone** [comment]
The workaround worked for me.

Thank you.

Best,
Maro
