### ISSUE TITLE
retrieving data underneath plot #3 - read ANI distribution

### ISSUE THREAD

**Issue by mcmahon-uw** [MrOlm/inStrain#131]
HI Matt,
Sorry this isn't actually an issue but just me trying to figure out how I can extract the data that are used to construct plot #3 (read ANI distribution).  I'd like to make some prettier plots with it (no offense!). I studied the section on "Raw data access and API", as well as the actual code, but alas my python skills are not strong enough to recapitulate the "prepare_read_ani_dist_plot(IS)" section to get what I want.

I thought maybe one of the "get_nonredundant_XXX_table()" functions would do it, but I'm not confident I understand what those do.

thanks so much for your help, and as always thanks for making such a powerful and amazing tool!!!

trina

**Comment by MrOlm** [comment]
Hi Trina,

Thanks for the kind words! I have plans in the works to make this data easier to access in the future, but unfortunately for now it does require a bit of python. Something like:

```
import inStrain
import inStrain.SNVprofile
import inStrain.plotting
import inStrain.plotting.mapping_plots

IS = inStrain.SNVprofile.SNVprofile("/path/to/inStrainOutputFolder")
Mdb =  inStrain.plotting.mapping_plots.prepare_read_ani_dist_plot(IS)
Mdb.to_csv("/path/to/output_table.csv", index=False)
```

where "/path/to/inStrainOutputFolder" is your inStrain output, and "/path/to/output_table.csv" is where you want the table created.I'm sorry this isn't more straightforward and please let me know if you hit problems

-Matt

**Comment by mcmahon-uw** [comment]
Actually this looks much easier than the workaround I was thinking about THANKS!!

-———-———
Katherine (Trina) McMahon
University of Wisconsin Madison

Sent from my mobile. Please excuse brevity and typos.
________________________________
