### ISSUE TITLE
conda/pip installations need phython <3.11

### ISSUE THREAD

**Issue by rrohwer** [MrOlm/inStrain#132]
Hi, I ran into some errors installing using both conda and pip (into clean conda environments), and was able to solve it by using python 3.10 instead of 3.11. Perhaps there is a mistake in the conda requirements? The conda error was very vague, but the pip error pointed me toward the python version as the issue. Hope this is helpful information! 

Robin

**Comment by MrOlm** [comment]
Thank you for pointing this out! I will look into and fix in the next update.

-Matt

**Comment by MrOlm** [comment]
I updated the conda requirements to remove some dependencies, and inStrain should now be able to be installed more easily. The changes should be reflected in `pip` immediately, but may take a while to be propagated to work with bioconda
