### ISSUE TITLE
instrain compare on multiple profiles

### ISSUE THREAD

**Issue by adijatj** [MrOlm/inStrain#133]
Hello, Can instrain comparison be done on more than two profiles mapped to the same fasta file? It appears the command only allows for a pairwise comparison based on the manual.

**Comment by MrOlm** [comment]
Sorry- the manual should be updated! Yes- you can compare as many profiles as you'd like, although more than 80 or so can end up taking a really long time

-Matt

**Comment by adijatj** [comment]
Thank you for your response, Matt. In this case, would the command syntax look like this: inStrain compare -i IS_output_1 IS_output_2 IS_output_3 IS_output_4 etc?

**Comment by MrOlm** [comment]
Yes that’s exactly correct

**Comment by rrohwer** [comment]
I have a follow-up question to this- I am comparing almost 500 profiles, so they cannot all load into RAM at once. Do you have advice on combining output from separately run comparisons? (Running separately could also let me multi-thread, as a bonus)

**Comment by MrOlm** [comment]
@rrohwer The way that I usually do this is parse the inStrain profile files to determine which genomes are present in each profile (min_breadthCov > 0.5) and then launch a separate inStrain compare job for each genome with only the profiles that have that genome (you can tell inStrain compare to only look at a single genome using the --genome argument).

Let me know if you have any questions about this
