### ISSUE TITLE
making plots is failing although everything else finishes without error

### ISSUE THREAD

**Issue by rrohwer** [MrOlm/inStrain#134]
When I run inStrain with `--skip_plot_generation` it finishes in about 2 hrs for a ~8GB bam and 128 threads (seems expected?) But when I include plotting, after 5 hours it is still running and only empty plots are generated. The only error that stands out seems like just a pandas deprecation message though:
```
/work/08922/rrohwer/ls6/miniforge3/envs/instrain/lib/python3.10/site-packages/inStrain/plotting/mapping_plots.py:161: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  counts = counts.append(pd.Series(np.zeros(lengt - len(counts))))
```
Unless.... that error under it is different? It looks like `lengt` might be a typo?

**Comment by rrohwer** [comment]
to clarify, this is during `inStrain profile`

**Comment by rrohwer** [comment]
I'm using `Python 3.10.9`. I got a different error using 3.11 (#132 )

**Comment by MrOlm** [comment]
OK- unfortunately my automated testing only goes up to Python version 3.8. I will work on adding support for plotting with later python versions, but in the meantime you may need to downgrade to version 3.7 or 3.8 for this plotting function to work properly

**Comment by rrohwer** [comment]
I will try this and let you know :) thanks!

**Comment by MrOlm** [comment]
I updated inStrain (v1.7.1) to fix this issue and I believe it will now work with up to python 3.10

Best,
Matt
