### ISSUE TITLE
-mb minimum breadth option in inStrain plot 

### ISSUE THREAD

**Issue by BenLRoss** [MrOlm/inStrain#138]
Hello,

I'm curious about the intended usage for `-mb` minimum breadth option in `inStrain plot` and which plots it affects. I couldn't find an explanation of it in the documentation.

Thanks,

Ben

**Comment by MrOlm** [comment]
Hi Ben,

There are a few plots that end up with big .pdfs with a page for each genome. That thresholds dictates the minimum breadth for a plot to be made for a particular genome.

Best,
Matt

**Comment by BenLRoss** [comment]
Ah, I see, thank you for the explanation!
