### ISSUE TITLE
samtools left out of v1.7.1 pip installation

### ISSUE THREAD

**Issue by rrohwer** [MrOlm/inStrain#140]
Thanks for the recent updates! I pip installed the new v1.7.1 version, and noticed that samtools is no longer installed as part of the package. It is easy enough to install it separately, but I just wanted to let you know because I think it was included before.

Thanks!
Robin

**Comment by MrOlm** [comment]
Hi Robin,

Thanks for the comment! I intentionally removed it as a dependency because it's not strictly required if you provide inStrain with a .bam file, it is confuses installation with conda on some systems. If I get some more comments like this I'll put it back though haha.

Thanks again!
Matt
