### ISSUE TITLE
merging custom genomes with an existing genome database using drep "-extraW " 

### ISSUE THREAD

**Issue by yan1365** [MrOlm/inStrain#145]
Hi Matt,

I want to prepare a dataset including custom MAGs and MAGs collected from the database. I noticed in the documentation, you mentioned "To prioritize your custom genomes over the database genomes, use the flag extra_weight_table within dRep.". However, I found out that the flag "extra_weight_table" is poorly documented (Path to a tab-separated file with two-columns, no headers, listing genome and extra score to apply to that genome.  

I am wondering what's a reasonable score to apply to for prioritizing custom MAGs?

Best,
Ming

**Comment by MrOlm** [comment]
Hi Ming,

It just depends how much you want to prioritize custom MAGs, which is a personal decision. If you want to always pick a custom MAG when available, assigning an extra weight of 100 to each custom MAG will do this. If you want to just give a slight preference, you can do something like 5. In my work I usually choose an extra weight of 20, which makes you pick custom genomes most of the time, unless the reference genome is way better.

Hope this helps,
Matt

**Comment by yan1365** [comment]
Hi Matt,

Thank you for your prompt response. That's all I wanted to know. 

Best,
Ming
