### ISSUE TITLE
>8h for`Step 2. Profile scaffolds`

### ISSUE THREAD

**Issue by liamfitzstevens** [MrOlm/inStrain#146]
I am running inStrain with 700 metagenomes and 3200 sSRGs (dRep 98%).`inStrain profile` `Step 2. Profile scaffolds` is profiling splits at a rate of 15 every 5 minutes. With the metagenome below as an example, this 15/5m rate = +1%/5m; which extrapolates to a run time of 500m (8.3h) to reach 100%.

```
***************************************************
    ..:: inStrain profile Step 1. Filter reads ::..
***************************************************

samtools index /ebio/abt3_scratch/lfitzstevens/LLMGPS_98810657028/inStrain/bowtie2/T268.bam /ebio/abt3_scratch/lfitzstevens/LLMGPS_98810657028/inStrain/bowtie2/T268.bam.bai -@ 8
Filtering reads: 100%|██████████| 5000/5000 [04:01<00:00, 20.72it/s]
Scaffold to bin was made using .stb file
3023 of 3212 genomes have less than 1x estimated coverage
998951 of the original 1095138 scaffolds are removed (998951 have a low coverage genome; 0 have no genome)
1.1% of pairs and 100.0% of singletons were removed during filtering
9,818,300 read pairs remain (2.922 Gbp)
***************************************************
.:: inStrain profile Step 2. Profile scaffolds ::..
***************************************************

Profiling splits:  30%|██▉       | 310/1038 [1:30:48<3:18:11, 16.33s/it]
```

This is much longer than I remember from my previous implementation, which was with a similar number of metagenomes but less than a third of the representative genomes (<1000 SRGs; dRep 95%). That more representative genomes translates to more compute makes sense, but I'd like to confirm the following:

With my parameters below, am I doing everything I can do ensure the shortest runtime possible? (I know `--database_mode` overwrites other flags but I left them there.)
```
profile: --min_cov 5 --min_freq 0.05 --min_genome_coverage 0.1 --min_read_ani 0.95 --database_mode --skip_plot_generation
compare: --min_cov 5 --min_freq 0.05 --ani_threshold 0.99999 --database_mode
```
Flags aside, I can think of 2 ways to reduce the runtime:
1) Switch from sSRGs to SRGs to reduce the number of rep. genomes.
     -> Not inclined because I want the best resolution possible.
2) Break up the inStrain run into 3 batches, with the sSRGs broken up into thirds but the same metagenomes in each batch, concatenating their outputs upon completion.

Ultimately if there's no way to further optimize the implementation, that's the way it is. Just want to make sure I'm configuring it as best one can.

**Comment by MrOlm** [comment]
Hi @liamfitzstevens ,

Good questions. For profile, the biggest things to do to improve speed are 1) add the flag `--skip_mm_profiling`, 2) set a higher ` --min_genome_coverage`, or 3) add more processes (`-p 10`). You're already doing more of these things, so unfortunately there's not a ton of room for improvement. You could increase the `--min_genome_coverage`, which will just reduce the number of scaffolds that make it to step 2, but that will come at decreased sensitivity.

You could also look at the `runtime_report` produced in the log file. This may give you an idea of what's taking so long. My guess is that you have a lot of short scaffolds that have a few reads mapped to them, which makes the multiprocessing efficiency really low. With that in mind, something you could do would be to run lots of `profile` jobs at once with one process each (`-p 1`) using a tool like `parallel`. Each run will still take the same about of time, but the time to run all 700 will be faster.

I think breaking up the inStrain run into 3 batches will take more total time that running one bigger job.

For compare, really the only thing that matters is the number of samples a genome is detected in, since it has to perform pair-wise comparisons. Up to 80 samples or so is usually OK, but after that it can take a while.

Let me know if you have other questions, and if you post your `runtime_report` in the log folder I'd be happy to help interpret.

Best,
Matt

**Comment by liamfitzstevens** [comment]
Hi Matt,

I'll keep `--skip_mm_profiling`, and not modify `--min_genome_coverage` for the reason you mentioned. Good to know about `parallel` - will keep that in my back pocket lest things end up taking truly prohibitively long. With respect to flags:

As mentioned earlier, I'm using `--database_mode` for `profile`, but this sets `--min_read_ani 0.92`, and I need `--min_read_ani 0.95` because my rep. genomes are sSRGs (dRep 98%), not SRGs (dRep 95%), correct? Let me know if I'm not understanding that correctly, otherwise I'll re-start it. Might a perk of this mean that fewer metagenome reads will qualify for mapping to sSRGs, which may reduce compute load? 


Looking through log files:

Should I add `- bioconda::coverm` to the `dependencies:` of my `instrain.yaml` (and you to inStrain's Bioconda recipe)? I'd think we should also add `- bioconda::numba`, but what's the rationale behind that if it _increases_ `filter_reads` runtime (as written in the log below)? Of note is that so far in my run, substantial metagenomes have their `instrain_profile` output written (as was the case for metagenome V153 below); how can that be if these two dependencies are missing?
```
23-04-06 14:34:24 DEBUG    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
23-04-06 14:34:24 DEBUG    ***Logger started up at /ebio/abt3_scratch/lfitzstevens/LLMGPS_98810657028/per-sample/V153/log/log.log***
23-04-06 14:34:24 DEBUG    Command to run inStrain was: /ebio/abt3_projects/HUBIF_metagenomics/bin/pipelines/llmgps/hubif/llmgps/.snakemake/conda/34110bee050231757c6a758cf269ff27_/bin/inStrain profile --min_>

23-04-06 14:34:24 DEBUG    inStrain version 1.7.1 was run

23-04-06 14:34:24 DEBUG    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

23-04-06 14:34:24 DEBUG    $$$$$$$$$$ DEPENDENCY REPORT $$$$$$$$$$
PYTHON
Running python v3.8.16 (default, Mar  2 2023, 03:21:46)
[GCC 11.2.0]

PROGRAM DEPENDENCIES
samtools...................... all good   (version=samtools 1.10) (location = /usr/bin/samtools)
coverm........................ ! NOT WORKING ! (version=na) (location = None)

PYTHON DEPENDENCIES
numba......................... ! NOT WORKING ! Not needed, but installing will increase filter_reads runtime
matplotlib.................... all good   (version=3.7.1) (location = /ebio/abt3_projects/HUBIF_metagenomics/bin/pipelines/llmgps/hubif/llmgps/.snakemake/conda/34110bee050231757c6a758cf269ff27_/lib/python3.8>
seaborn....................... all good   (version=0.12.2) (location = /ebio/abt3_projects/HUBIF_metagenomics/bin/pipelines/llmgps/hubif/llmgps/.snakemake/conda/34110bee050231757c6a758cf269ff27_/lib/python3.>
numpy......................... all good   (version=1.24.2) (location = /ebio/abt3_projects/HUBIF_metagenomics/bin/pipelines/llmgps/hubif/llmgps/.snakemake/conda/34110bee050231757c6a758cf269ff27_/lib/python3.>
Bio........................... all good   (version=1.74) (location = /ebio/abt3_projects/HUBIF_metagenomics/bin/pipelines/llmgps/hubif/llmgps/.snakemake/conda/34110bee050231757c6a758cf269ff27_/lib/python3.8/>
pysam......................... all good   (version=0.20.0) (location = /ebio/abt3_projects/HUBIF_metagenomics/bin/pipelines/llmgps/hubif/llmgps/.snakemake/conda/34110bee050231757c6a758cf269ff27_/lib/python3.>
pandas........................ all good   (version=1.5.3) (location = /ebio/abt3_projects/HUBIF_metagenomics/bin/pipelines/llmgps/hubif/llmgps/.snakemake/conda/34110bee050231757c6a758cf269ff27_/lib/python3.8>
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

23-04-06 14:34:24 INFO     Indexing /ebio/abt3_scratch/lfitzstevens/LLMGPS_98810657028/inStrain/bowtie2/V153.bam
23-04-06 14:34:28 INFO     ***************************************************
    ..:: inStrain profile Step 1. Filter reads ::..
***************************************************

23-04-06 14:34:28 DEBUG    Checkpoint main_profile filter_reads start 406966272
23-04-06 14:34:28 DEBUG    Checkpoint FilterReads load_fasta start 407121920
23-04-06 14:35:28 DEBUG    Checkpoint FilterReads load_fasta end 7618990080
23-04-06 14:35:28 DEBUG    Checkpoint FilterReads get_paired_reads_multi start 7618990080
23-04-06 14:35:29 DEBUG    Checkpoint FilterReads multiprocessing start 7619706880
23-04-06 14:35:29 DEBUG    Establishing processes
23-04-06 14:35:34 DEBUG
WorkerLog GetPairedReads G0290_vitroT0__metabat2__High_005__CONTIG145 start 511934464 1680784532.6910372 86202
WorkerLog GetPairedReads G0290_vitroT0__metabat2__High_005__CONTIG145 end 765571072 1680784534.0862567 86202
WorkerLog GetPairedReads V017_vitroT0__metabat2__High_015__CONTIG688 start 765571072 1680784534.0863473 86202
WorkerLog GetPairedReads V017_vitroT0__metabat2__High_015__CONTIG688 end 765571072 1680784534.0864463 86202
```
... other metagenomes fail, like V099 below, because they don't have any output written. Though it could be related to the aforementioned dependencies, I suspect it's because in the case of these two examples, V149 (success) had 4.5M metagenome reads, whereas V099 (failure) had 10M. I will increase the time allocated for `profile` in our department's inStrain Snakefile. In other words, the error _is_ because the output isn't being written, but that's because the pipeline doesn't give enough time for big metagenome jobs, not because the file system is lagging.
```
MissingOutputException in rule instrain_profile in line 142 of /ebio/abt3_projects/HUBIF_metagenomics/bin/pipelines/llmgps/hubif/llmgps/./bin/instrain/Snakefile:
Job Missing files after 90 seconds. This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait:
/ebio/abt3_scratch/lfitzstevens/LLMGPS_98810657028/per-sample/V099/output/V099_genome_info.tsv
/ebio/abt3_scratch/lfitzstevens/LLMGPS_98810657028/per-sample/V099/output/V099_scaffold_info.tsv
/ebio/abt3_scratch/lfitzstevens/LLMGPS_98810657028/per-sample/V099/output/V099_gene_info.tsv
/ebio/abt3_scratch/lfitzstevens/LLMGPS_98810657028/per-sample/V099/output/V099_read_report.tsv
/ebio/abt3_scratch/lfitzstevens/LLMGPS_98810657028/per-sample/V099/output/V099_SNVs.tsv
/ebio/abt3_scratch/lfitzstevens/LLMGPS_98810657028/per-sample/V099/output/V099_linkage.tsv
/ebio/abt3_scratch/lfitzstevens/LLMGPS_98810657028/per-sample/V099/output/V099_mapping_info.tsv
/ebio/abt3_scratch/lfitzstevens/LLMGPS_98810657028/per-sample/V099/raw_data/clonT.hd5
/ebio/abt3_scratch/lfitzstevens/LLMGPS_98810657028/per-sample/V099/raw_data/clonTR.hd5
/ebio/abt3_scratch/lfitzstevens/LLMGPS_98810657028/per-sample/V099/raw_data/covT.hd5
/ebio/abt3_scratch/lfitzstevens/LLMGPS_98810657028/per-sample/V099/raw_data/Rdic.pickle
/ebio/abt3_scratch/lfitzstevens/LLMGPS_98810657028/inStrain/bowtie2/V099.bam.bai
/ebio/abt3_projects/HUBIF_metagenomics/data/pipelines/llmgps/hubif/mother_infant_instrain/llmgps_output_736metagenomes_3212srgs/benchmarks/instrain/profile/V099.txt completed successfully, but some output files are missing. 7373
```

Thanks for the offer to help interpret the log files. The aforementioned slow-but-successful and failed-but-I-think-I-know-why metagenomes' logs are here (file sizes exceeds Git's 25MB limit):
https://owncloud.tuebingen.mpg.de/index.php/s/ZXc6wxyJ6bCkTKR

Best,
Liam

**Comment by liamfitzstevens** [comment]
The metagenomes that were failing at `profile` was because `No scaffolds detected; see above message and log`. I simply removed them and `profile` successfully ran (and only needed 2 days!). So `profile` runtime is not actually an issue, I suppose all thanks to parallelization.  Your feedback would be great on the following:

1) Am I correct that since my rep. genomes are sSRGs (dRep 98%), that means I can't use `--database_mode` (because that drops `--min_read_ani` too low to 0.92)?
2) If 1 = yes, do you agree that I need to re-run `profile`, and that the following parameters would be optimal?
```
profile: --min_cov 5 --min_freq 0.05 --min_genome_coverage 1 --min_read_ani 0.95 --skip_mm_profiling --skip_plot_generation
```

**Comment by MrOlm** [comment]
Hi Liam,

Great glad it's working for you, and yes that command looks great! I will say that keeping the default database_mode paramaters would probably be fine too, but your parameters are more optimal.

Best,
Matt
