### ISSUE TITLE
updata docker versin

### ISSUE THREAD

**Issue by adobe7105** [MrOlm/inStrain#152]
the latest version of instrain on docker is 1.6 ,please updata 

please,please,please,please

**Comment by MrOlm** [comment]
Hello- I haven't been maintaining that Docker, I've been using the ones here - https://quay.io/repository/biocontainers/instrain?tab=tags&tag=latest

Will that work for you?

Best,
Matt

**Comment by adobe7105** [comment]
You’re the best.(˚ ˃̣̣̥᷄⌓˂̣̣̥᷅ )，thank you so much。
 ♪（＾∀＾●）ﾉｼ （●′∀｀）♪ 
this image works fine。
