### ISSUE TITLE
How to calculate the pN/pS value of similar function genes

### ISSUE THREAD

**Issue by haihao999** [MrOlm/inStrain#155]
Hi,Matt
When evaluating the pN/pS values of similarly functioning genes, is it  more appropriate to treat them as one long sequence or taking an average of all the genes? 
Thanks!
yanpeng

**Comment by MrOlm** [comment]
Hi @haihao999 - that's a great question. I think both of the approaches you describe would work fine, but I'm not sure which is the "correct" way to do it.

Best,
Matt
