### ISSUE TITLE
inStrain plot not generating plots 2 and 7

### ISSUE THREAD

**Issue by cusoiv** [MrOlm/inStrain#156]
Hi @MrOlm, 

I seem to have run into a problem with inStrain plot. I wanted to generate a set of plots from the .IS object that I had previously created (which included also all the raw data, etc), but had problems with generating plots 2 and 7. This does not happen if I don't skip the plot generation in the inStrain profile -- then I get figures 2 and 7 just fine.

making plots 1, 2, 3, 4, 5, 6, 7, 8, 9
Plotting plot 1
Plotting plot 2
Failed to make plot #2: 'scaffold'
Plotting plot 3
Plotting plot 4
Skipping plot 5 - you don't have all required information. You need to run inStrain genome_wide first
Plotting plot 6
Plotting plot 7
Failed to make plot #7: 'scaffold'
Skipping plot 8 - you don't have all required information. You need to run inStrain profile_genes first
Plotting plot 9

It would be great if you could help in resolving this issue! 

Thanks a lot,
Annie

**Comment by MrOlm** [comment]
Hi @cusoiv -

Could you please run the command with `-d` (debug mode)? That will add some more output to explain what's going wrong. It would also be helpful to have the log file to try and troubleshoot this.

Best,
Matt

**Comment by MrOlm** [comment]
OK thank you for this. One more question- in your `raw_data` folder there should be a file called `raw_linkage_table.csv.gz`. Could you please send that to me? That file is at the heart of this bug.

Best,
Matt

**Comment by MrOlm** [comment]
Hi Annie,

I don't believe attachments work in this way- you can either email me the file directly or upload it to GitHub (here https://github.com/MrOlm/inStrain/issues/156).

Thank you!
MO

**Comment by cusoiv** [comment]
Hi Matt,

Thanks! Uploading now.
[raw_linkage_table.csv.gz](https://github.com/MrOlm/inStrain/files/12175110/raw_linkage_table.csv.gz)

Best,
Annie

**Comment by MrOlm** [comment]
OK- thank you for all of this. I have now confirmed that I understand the bug that's causing this issue, and I will fix it in the  next inStrain update.

Thanks again!
Matt

**Comment by MrOlm** [comment]
I believe this bug is fixed in version 1.7.6, released a few minutes ago

-MO

**Comment by cusoiv** [comment]
Thank you Matt! This is incredibly helpful!
