### ISSUE TITLE
genes with allele frequency differences

### ISSUE THREAD

**Issue by haihao999** [MrOlm/inStrain#160]
Hi,Matt
I have a simple question, if I want to find genes with allele frequency differences, do I compare the con_freq of this locus, or the average of the con_freq of all loci of this gene？ thanks!

**Comment by MrOlm** [comment]
Hi @haihao999 -

This is a good question, but more complex than you'd initially think. There are many, many different ways to compare allele frequency differences, and both of the method you mention are sometimes used. It really depends on the question you want to answer.

I will also mention that you might want to compare the "ref_freq" instead. "con_freq" is the frequency of the consensus base (the most common base), so the consensus base can change from sample to sample. "ref_freq" is based on the reference genome, though, so it will be reporting the frequency of the same base in each sample.

Best,
Matt

**Comment by haihao999** [comment]
Hi Matt
Thank you very much for your tools and advice, I aim to find out the genes that are adapted to both ammonium concentrations, I will try it out and hopefully it will be useful!
Best,
yanpeng
