### ISSUE TITLE
Issue in statistical analysis of nucleotide diversity.

### ISSUE THREAD

**Issue by ChenTianYi99** [MrOlm/inStrain#162]
Hi,
I know that nucleotide diversity will be blank if no positions have a base over the minimum coverage. So i wonder if the NA value should be 0 or be dismissed (for example in R, na.rm=TRUE should be set) in downstream statistical analyses.

Looking forward to your reply. Thank you in advance.
Sincerely

**Comment by MrOlm** [comment]
Hi @ChenTianYi99 - the answer here depends on the exact statistical task you're performing, but in general I remove these values rather then set them to 0.

Best,
Matt

**Comment by ChenTianYi99** [comment]
Hi, Matt. 
Thank you very much for your response. I will try to remove the NA values in my statistical analyses.

Best
Tianyi Chen
