### ISSUE TITLE
DEBUG:no_length will not be considered as part of the genime

### ISSUE THREAD

**Issue by Xiaoxin9115** [MrOlm/inStrain#163]
During our inStrain compare process, we encountered a DEBUG message indicating that "no_length will not be considered as part of the genome." However, the length information is displayed in the STB file. 
We want to know what is the reason for this. Whether effect our result of compare?
![image](https://github.com/MrOlm/inStrain/assets/126141055/a406fb12-8d4b-4804-875b-1ed532e36fe6)
![image](https://github.com/MrOlm/inStrain/assets/126141055/5177e9ef-d76d-4cad-81c2-4de56f629313)

**Comment by MrOlm** [comment]
Hi @Xiaoxin9115 - Could you provide the log file from the run?

Thanks,
Matt

**Comment by Xiaoxin9115** [comment]
[Uploading log.log…]()

**Comment by Xiaoxin9115** [comment]
[log.log](https://github.com/MrOlm/inStrain/files/13233337/log.log)

**Comment by MrOlm** [comment]
OK- what this error means is that that scaffold is not present in the IS file (so was not originally provided during the inStrain profile run). So the line:

`23-10-30 20:26:38 DEBUG    FAILURE StbError CowSGB-1_c1 CowSGB-1.fa no_length will not be considered as part of the genome`

is saying that your stb file says scaffold `CowSGB-1_c1` should be in genome `CowSGB-1.fa`, but the scaffold `CowSGB-1_c1` wasn't provided in the .fasta file that was used to make the inStrain profile objects

-Matt
