### ISSUE TITLE
about inStrain profile with KeyError: 'version'

### ISSUE THREAD

**Issue by ZT-ls** [MrOlm/inStrain#165]
Hi, i'm encounting a issue when running  inStrain profile, it raised the keyError:'version' which like this
![1699082831702](https://github.com/MrOlm/inStrain/assets/38306935/42476878-88aa-4197-b7a3-5d0eb922195d)
is there any ways to deal with it? thank you very much

**Comment by MrOlm** [comment]
Hi @ZT-ls - this seems to be a stange bug with the python package "pandas" that I've never seen before.

I would recommend re-installing inStrain in a new conda environment, which should give you a fresh installation of pandas.

Best,
Matt

**Comment by ZT-ls** [comment]
hi Matt， thank you very much for your response, actually, i tried a new conda environment  and the error still existed , then i re-installed the latest annaconda3, but the issue still happened. i agree with you on the pandas version issue, can you give me some matched conda version and pandas version that might work? i tried different version of python, and i found python that below or 3.10 might installed sucessfully but encounted the pandas issue,the python 3.11 might not be succesfully installed. can you please tell me the latest python version or pandas version that inStrain works? thank you very much Matt
                                                                                                                                                                                                Best.
                                                                                                                                                                                                ZT

**Comment by ZT-ls** [comment]
i mean, could you tell me one or two version compositions of python or conda and pandas that you used which succesfully worked, thank you very much

**Comment by MrOlm** [comment]
Hi @ZT-ls -

Here's the details of one of my current, working inStrain installations:

```
$ inStrain check_deps
$$$$$$$$$$ DEPENDENCY REPORT $$$$$$$$$$
PYTHON
Running python v3.9.12 (main, Jun  1 2022, 06:34:44)
[Clang 12.0.0 ]

PROGRAM DEPENDENCIES
samtools...................... ! NOT WORKING ! (version=na) (location = None)
coverm........................ all good   (version=coverm 0.6.0) (location = /Users/mattolm/.cargo/bin/coverm)

PYTHON DEPENDENCIES
numba......................... ! NOT WORKING ! Not needed, but installing will increase filter_reads runtime
matplotlib.................... all good   (version=3.7.2) (location = /Users/mattolm/mambaforge/envs/python3.9_instrain/lib/python3.9/site-packages/matplotlib/__init__.py)
seaborn....................... all good   (version=0.12.2) (location = /Users/mattolm/mambaforge/envs/python3.9_instrain/lib/python3.9/site-packages/seaborn/__init__.py)
numpy......................... all good   (version=1.25.1) (location = /Users/mattolm/mambaforge/envs/python3.9_instrain/lib/python3.9/site-packages/numpy/__init__.py)
Bio........................... all good   (version=1.74) (location = /Users/mattolm/mambaforge/envs/python3.9_instrain/lib/python3.9/site-packages/Bio/__init__.py)
pysam......................... all good   (version=0.21.0) (location = /Users/mattolm/mambaforge/envs/python3.9_instrain/lib/python3.9/site-packages/pysam/__init__.py)
pandas........................ all good   (version=2.0.3) (location = /Users/mattolm/mambaforge/envs/python3.9_instrain/lib/python3.9/site-packages/pandas/__init__.py)
```

Best,
Matt

**Comment by ZT-ls** [comment]
there is note that it was not succefully installed for instrain by conda install, then i just selected different versions of python in conda environmant and installed instrain using pip, "conda install inStrain" did't return error but it took a long time to finish

**Comment by ZT-ls** [comment]
ok, thank you, Matt

**Comment by ZT-ls** [comment]
hi Matt, i tried same version of pandas but the error still existed, according to the Traceback, is there any possibility that version here is the inStrain version?  
![4a6e9583225c09dcd6bbafba03b0858](https://github.com/MrOlm/inStrain/assets/38306935/445e5b2f-3c70-435b-a240-4b9e8182bea3)
just like the figure posted where the code marked, i installed the latested vesion of inStrain, or maybe the script didnot catched the  version info?

**Comment by MrOlm** [comment]
Hi @ZT-ls - I see. What is the commend you're trying to run? It seems that you're passing inStrain what it thinks is an inStrain profile folder, but that folder doesn't have the necessary attributes file in the `raw_data` folder.

Best,
Matt

**Comment by ZT-ls** [comment]
thanks  Matt， this issue appeared when running inStrain profile, is it necessary for me to download some folder? this time i installed inStrain through mamba

**Comment by MrOlm** [comment]
To run inStrain profile you don't need to have a folder, but this error makes me think that the output folder you are telling inStrain to create already exists, and that is causing the problem.

Make sure that the output folder you specify does not already exist.

Best,
Matt

**Comment by ZT-ls** [comment]
yes, Matt, actually, i created the output folder before running inStrain profile, ok, thank you Matt, very appreciate it !
