### ISSUE TITLE
clarity regarding strain_clusters.tsv

### ISSUE THREAD

**Issue by ShailNair** [MrOlm/inStrain#166]
Hi,

Thanks for the all the hard work that has been put into developing instrain package. It has substantially aided my research into exploring the genetic diversity within the population i am currently studying. I conducted a comparison of the Instrain profiles of metagenomic assembled virus contigs/genomes across days, which were dereplicated at 95% ANI. I got the following strain_clusters.tsv table:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Admin/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Admin/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

cluster | sample | genome
-- | -- | --
1_1 | 100.days.sort.bam | c_000000000018.fasta
1_1 | 250.days.sort.bam | c_000000000018.fasta
1_1 | 400.days.sort.bam | c_000000000018.fasta
1_1 | 450.days.sort.bam | c_000000000018.fasta
1_2 | Original.bottle.sort.bam | c_000000000018.fasta
2_1 | 400.days.sort.bam | c_000000000022.fasta
2_1 | 450.days.sort.bam | c_000000000022.fasta
6_1 | 100.days.sort.bam | c_000000000058.fasta
6_2 | 250.days.sort.bam | c_000000000058.fasta
6_3 | 400.days.sort.bam | c_000000000058.fasta
6_3 | 450.days.sort.bam | c_000000000058.fasta
6_4 | Original.bottle.sort.bam | c_000000000058.fasta

</body>

</html>

Based on the provided description, I infer that the number preceding the underscore in "cluster" column represents cluster number/serial number. While the number after the underscore represents strain number. For example, in the case of "c_000000000018.fasta," the strain appears to be similar in the first four samples but different in the last one. Likewise, concerning "c_000000000058.fasta," the strains differed across all samples except for '400.days.sort.bam' and '450.days.sort.bam.'

Is this interpretation correct?

**Comment by MrOlm** [comment]
Hi @ShailNair - yes, your interpretation is correct.

Best,
Matt

**Comment by ShailNair** [comment]
Thanks Matt
