### ISSUE TITLE
Inconsistency between results of “inStrain quick_profile” and “inStrain profile" 

### ISSUE THREAD

**Issue by haihao999** [MrOlm/inStrain#170]
Hi Matt,
   I find it surprising that these two results are inconsistent in terms of coverage and width, so how do I choose., especially on this coverage, the value becomes smaller

quick profile:
   0.97237   119.117
   0.96929   131.667
 profile :  *genome_info.tsv
  0.970865   74.04536
  0.968777    63.45396

**Comment by MrOlm** [comment]
Hi @haihao999 -

The biggest difference between the two will come down to the read filtering step. Your results in particular seem to suggest that there are a lot of reads that map to this genome that are pretty divergent from the genome itself (these reads are retained with quick_profile and removed with profile). Which one you want to use depends on your research question.

Best,
Matt
