### ISSUE TITLE
Questions about read coverage and breadth filtration.

### ISSUE THREAD

**Issue by ChenTianYi99** [MrOlm/inStrain#179]
Hi,
I want to analyze viral populations with >10× average read depth coverage and >70% length of genome covered for microdiversity analyses. 
I wonder if i should set MIN_COV to 10 and filter by "breadth" in scaffold_info.tsv (or set other relevant parameters).

Thanks in advance.

**Comment by MrOlm** [comment]
Hi @ChenTianYi99 - if I were you I would run with default parameters, then filter the scaffold_info.tsv to coverage > 10 and breadth > 0.7. No need to adjust the MIN_COV when running the program.

Best,
Matt
