### ISSUE TITLE
instrain profile step3

### ISSUE THREAD

**Issue by Biofarmer** [MrOlm/inStrain#180]
Hi Dr. Olm,
I am using the inStrain v1.6.3 with code as below:
inStrain profile file.sam reference.fna -o file.IS -p 24 -g reference.genes.fna -s reference.stb --database_mode --skip_plot_generation
The output files are produced, but I haver one warning in the log 
"/anaconda3/envs/instrain_163/lib/python3.8/site-packages/inStrain/genomeUtilities.py:948: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  cov = pd.Series(index=np.arange(slen))"
May I ask why this warning occur, and is there any influence on the results?
Additionally, there are "Step 1" to "Step 5" in the log, but without "Step 3", may I ask whether this is normal, why is there no "Step 3"? 

Thank you very much.
Wang

**Comment by MrOlm** [comment]
Hi Wang,

That warning will not cause any problems, and the most up-to-date version so inStrain won't have that warning displayed at all.

Step 3 is profiling genes. Did you end up gene-level information in your output folder?

Matt

**Comment by Biofarmer** [comment]
Hi Dr. Olm, 
Thank you very much for your reply. That's great that this warning has no any effect on the output.
Yes, there is file ending with "IS_gene_info.tsv" in the output folder, and the other 5 files include: IS_genome_info.tsv, IS_linkage.tsv, IS_mapping_info.tsv, IS_scaffold_info.tsv, and IS_SNVs.tsv. Is inStrain running well?
I also checked the log file from https://github.com/MrOlm/inStrain/issues/167, produced inStrain v1.7.1, and there is no Step 3 as well.
Wang

**Comment by Biofarmer** [comment]
Hi Dr. Olm, is there any issue with my running? Thanks, Wang

**Comment by MrOlm** [comment]
Sorry I lost track of this- no, there is no issue with your run! I'm not sure why that comment didn't make it through, but if you got the output files, it doesn't matter and certainly won't impact the run

**Comment by Biofarmer** [comment]
> Sorry I lost track of this- no, there is no issue with your run! I'm not sure why that comment didn't make it through, but if you got the output files, it doesn't matter and certainly won't impact the run

That's great, and thank you very much for confirming.

**Comment by Biofarmer** [comment]
Hi Dr. Olm, 
One small question about the files in the output folder from inStrain profile: sometimes files for linkage.tsv and SNVs.tsv are zipped, is that normal? and inStrain zips them automatically due to their large size?
Thank you very much.
Wang

**Comment by MrOlm** [comment]
Yes that's correct. There's also an option to always compress the files, if that's what you prefer

**Comment by Biofarmer** [comment]
> Yes that's correct. There's also an option to always compress the files, if that's what you prefer

Thank you for your confirmation, and additional advice.
