### ISSUE TITLE
unable to lock file, errno = 37, error message = 'No locks available'

### ISSUE THREAD

**Issue by 473021677** [MrOlm/inStrain#183]
Hi,
    I am trying to run inStrain profile, but I have encountered some problems. It shows "OSError: [Errno 37] Unable to synchronously create file (unable to lock file, errno = 37, error message = 'No locks available')". And I have run the command HDF5_USE_FILE_LOCKING='FALSE' before running inStrain. However, the problem can not be fixed. I have appended the nohup.out.txt file. I need your help. Thanks.

Best regards
[nohup.out.txt](https://github.com/MrOlm/inStrain/files/15417657/nohup.out.txt)

**Comment by MrOlm** [comment]
Hi @473021677 -

Unfortunately this is an issue with how your operating system is interacting with the python multiprocessing module; I don't think there's anything I can do to fix it.

However, if you run inStrain with a single process (`-p 1`) it won't multiprocess at all, which should make the problem go away.

Best,
Matt

**Comment by 473021677** [comment]
I will have a try. Thanks for your help.
