### ISSUE TITLE
instrain_compare clustering failure

### ISSUE THREAD

**Issue by elisacaffrey** [MrOlm/inStrain#184]
Hi Matt,
 I am running instrain_compare. The run finished without a problem, but only generated the genomeWide_compare.tsv and comparisonsTable.tsv and not the strain_clusters.tsv. The inStrainCompare_dendrograms.pdf file was created but is corrupted, so I cannot open it to visualize. When I checked the log.log, it reports a clustering failure for all genomes (screenshot of the end below).
<img width="1106" alt="Screenshot 2024-05-23 at 9 12 44 AM" src="https://github.com/MrOlm/inStrain/assets/16585164/73013a15-e067-4fdc-9d3e-1191304a361e">

I ran the same command twice with the same output. What do you think might be the issue?

Thank you!
Elisa

**Comment by MrOlm** [comment]
Hi @elisacaffrey - hmmm interesting. Can you send me the command used to run inStrain compare?

Thanks,
Matt

**Comment by elisacaffrey** [comment]
Sure thing, here it is:
`nextflow run /home/mattolm/user_data/Nextflow/nf-core-genomeresolvedmetagenomics/aux_instrain_compare.nf -with-report report_compare_batch0105_v2.html --input instraincompare_batch0105_05172024.csv --outdir batch09_results_v3/ --stb s3://sonn-highavail/databases/MiFoDB/MiFoDB_beta/MiFoDB_beta_v3/MiFoDB_beta_v3_prok.stb`

**Comment by MrOlm** [comment]
Ah I see- try adding `--is_compare_args " --database_mode"` to your nextflow command

**Comment by elisacaffrey** [comment]
Great, thank you! I'll try running the updated command now.

**Comment by elisacaffrey** [comment]
Run complete and problem solved, thank you!
