### ISSUE TITLE
command "instrain profile " export that some plots can't make

### ISSUE THREAD

**Issue by Quzelei** [MrOlm/inStrain#186]
Failed to make plot #5: lineplot() takes from 0 to 1 positional arguments but 2 were given
Plotting plot 6
Failed to make plot #6: barplot() takes from 0 to 1 positional arguments but 2 positional arguments (and 1 keyword-only argument) were given
Plotting plot 7

**Comment by MrOlm** [comment]
What version of inStrain are you running?

**Comment by Quzelei** [comment]
> What version of inStrain are you running?

docker://quay.io/biocontainers/instrain:1.5.5--pyhdfd78af_0
