### ISSUE TITLE
Error for using conda install

### ISSUE THREAD

**Issue by Xinpeng021001** [MrOlm/inStrain#190]
Hi,

Thank you for providing such a great tool! I'm trying to use bioconda to install it and it succeed, however, when I tried to run the tool it gave me the error with h5py. I checked the version of h5py and it shows as 3.7.0, which should be 3.11.0. Could you please check if it was an error in anaconda?

Best,

**Comment by MrOlm** [comment]
Hi,

Thank you for reaching out and for using the tool! I don’t maintain the Bioconda package, so unfortunately, I’m unable to address issues related to it directly. You might want to report this issue to the Bioconda team or the maintainer of the specific recipe for this tool.

Best,
Matt
