### ISSUE TITLE
Clustering Error, StbError, and Memory Usage for inStrain Compare

### ISSUE THREAD

**Issue by gillianpatton** [MrOlm/inStrain#192]
Hi! During my run of inStrain compare, I'm hitting a few issues that I'm not sure what to do with. My input data are MAGs assembled from short and long read sequencing of infant and adult gut microbiome samples. The first issue (screenshot below) is a clustering error that's showing up for a minority of the genomes (9 out of 97) when I run inStrain compare for one individual with multiple timepoints. This error doesn't stop inStrain compare from running, but I just want to make sure it isn't an issue. My current theory is that maybe it's being caused by the presence of MAGs that are the only representative of their species.

<img width="919" alt="ClusteringErrorinStrain" src="https://github.com/user-attachments/assets/d4338291-0928-4678-955b-77cbef1eb8bf">

The second issue I'm having is a bit more concerning. I'm getting an StbError for around 1200 contigs (screenshot below). Again, this error doesn't affect the job's completion status, but none of the possible explanations posited by previous posts on this forum seem to explain why this error is showing up for my samples. The contig names match in the fasta, bam, and stb files, and the contigs have length in both the fasta and the bam files. The contig names for the contigs throwing this error aren't any longer than those that don't throw an error, and the contig length also doesn't seem to be any different. I also didn't run --database-mode for inStrain profile or inStrain compare, which I've read can cause this error. I'm not sure if this error is even a problem for me, but I'd love more ideas for what to look for as the cause.

<img width="919" alt="StbErrorinStrain" src="https://github.com/user-attachments/assets/db7119b8-2ebb-485a-94e6-392709e5f46f">

The last problem I'm having is that I have a sample set comprised of an individual with more timepoints (21 timepoints as compared to the 6 for the individual I describe above) that takes an insane amount of memory to run through inStrain compare. I'm trying to compare all of these timepoints to each other, and compare is taking 300-400 GB of memory to run, even with the --database-mode flag. Even with this increased memory amount, the job stalled out (it kept running but used 0.0% of its CPUs) on its last run. I have attached the error and log files if you have any idea of what could have caused this. I also wanted to ask what complexity of samples inStrain was designed to handle; I'm debating separating my MAGs out by taxon and running inStrain separately for each taxon to reduce the number of comparisons necessary for compare.

Any advice that you can provide would be super helpful!

The error and log files are attached here. 08-2 is the individual referenced for my first two issues, and 20-2 is the individual referenced for the third.
[08-2_log.log](https://github.com/user-attachments/files/17285043/08-2_log.log)
[20-2_log.log](https://github.com/user-attachments/files/17285044/20-2_log.log)
[y_09_instrain-compare_08-2_error.txt](https://github.com/user-attachments/files/17285051/y_09_instrain-compare_08-2_error.txt)
[y_09_instrain-compare_20-2_error.txt](https://github.com/user-attachments/files/17285052/y_09_instrain-compare_20-2_error.txt)

**Comment by MrOlm** [comment]
Discussed over email- let me know if you still have more questions!
