### ISSUE TITLE
Regenerating Tables with Different Parameters (rarefied nucleotide diversity)

### ISSUE THREAD

**Issue by shahdelnaggar** [MrOlm/inStrain#199]
Hello @MrOlm, 

I've used inStrain profile on many samples and would like to recalculate rarefied nucleotide diversity (in output/genome_info.tsv) with a different `--rarefied_coverage` parameter. 

What is the best way to do this using the raw_data without having to rerun inStrain again from scratch? 

Thanks for your help!

Best,
Shahd

**Comment by MrOlm** [comment]
Hi @shahdelnaggar - apologies but the only way to change that parameter is to re-run from scratch.

Best,
Matt

**Comment by shahdelnaggar** [comment]
Hi @MrOlm - got it, thanks for the quick response!

Best,
Shahd
