### ISSUE TITLE
Can inStrain be used for profiling metagenomes containing eukaryotic populations

### ISSUE THREAD

**Issue by DOieGYuan** [MrOlm/inStrain#201]
Dear developer:

Thank you for creating this incredible tool—it’s been a great help in many ways!

I’m wondering if inStrain can be used to profile metagenomes that include eukaryotic populations, such as those found in algae-bacteria communities.

Looking forward to your guidance!

Best regards,
Yuan

**Comment by MrOlm** [comment]
Hi @DOieGYuan - yes it can! I've used it many times for that. You just need to make sure to consider that fact that polyploidy is a think with some eukaryotes, which impacts how you interpret some of the results.

Best,
Matt
