### ISSUE TITLE
Whether sambamba influence the results

### ISSUE THREAD

**Issue by 473021677** [MrOlm/inStrain#202]
Hi,
   I am yuanyang, a postdoc. I am major in microbial evolutionary patterns and processes. I am using inStrain to profile microbial population microdiveristy. The program have run normally and the resulting files have been obtained. However, I have one doubt about the log file. The log file shows "PROGRAM DEPENDENCIES
samtools...................... all good   (version=/share1/home/yuzhenm/software/miniconda3/bin/samtools: /share1/home/yuzhenm/software/miniconda3/bin/../lib/libtinfow.so.6: no version information available (required by /share1/home/yuzhenm/software/miniconda3/bin/samtools)) (location = /share1/home/yuzhenm/software/miniconda3/bin/samtools)
coverm........................ all good   (version=coverm 0.7.0) (location = /share1/home/yuzhenm/software/miniconda3/bin/coverm)
sambamba...................... ! NOT WORKING ! (version=na) (location = None)".
I am not sure whether sambamba influence the results and need your help. Thanks.

Best regards,
Yang Yuan

**Comment by MrOlm** [comment]
Hi @473021677 - No, you don't need sambamba. It will make some operations faster (very rarely), but will not change the output in any way.

Matt

**Comment by 473021677** [comment]
Thanks for your explanation very much.
