### ISSUE TITLE
"KeyError: 'mm'" during plotting

### ISSUE THREAD

**Issue by apcamargo** [MrOlm/inStrain#21]
I'm getting an `KeyError: 'mm'` when inStrain is writing the output plots. I suspect that this may be caused by this genome having a low read coverage in this specific sample, as I didn't get this error with other genomes.

```
making plots 1, 2, 3, 4, 5, 6, 7, 8, 9
Plotting plot 1
Plotting plot 2
Failed to make plot #2: 'scaffold'
Plotting plot 3
Skipping plot 4 - you don't have all required information. You need to run inStrain genome_wide first
Traceback (most recent call last):
  File "/global/homes/a/acamargo/SCRATCH/.environments/instrain/lib/python3.6/site-packages/inStrain/plottingUtilities.py", line 1422, in allele_freq_plot_from_IS
    db = db.sort_values('mm').drop_duplicates(subset=['scaffold', 'position'], keep='last')\
  File "/global/homes/a/acamargo/SCRATCH/.environments/instrain/lib/python3.6/site-packages/pandas/core/frame.py", line 4927, in sort_values
    k = self._get_label_or_level_values(by, axis=axis)
  File "/global/homes/a/acamargo/SCRATCH/.environments/instrain/lib/python3.6/site-packages/pandas/core/generic.py", line 1692, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'mm'
Skipping plot 5 - you don't have all required information. You need to run inStrain genome_wide first
Traceback (most recent call last):
  File "/global/homes/a/acamargo/SCRATCH/.environments/instrain/lib/python3.6/site-packages/inStrain/plottingUtilities.py", line 1463, in linkage_decay_from_IS
    db = db.sort_values('mm').drop_duplicates(subset=['scaffold', 'position_A', 'position_B'], keep='last')\
  File "/global/homes/a/acamargo/SCRATCH/.environments/instrain/lib/python3.6/site-packages/pandas/core/frame.py", line 4927, in sort_values
    k = self._get_label_or_level_values(by, axis=axis)
  File "/global/homes/a/acamargo/SCRATCH/.environments/instrain/lib/python3.6/site-packages/pandas/core/generic.py", line 1692, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'mm'
Plotting plot 6
/global/homes/a/acamargo/SCRATCH/.environments/instrain/lib/python3.6/site-packages/inStrain/plottingUtilities.py:762: RuntimeWarning: divide by zero encountered in double_scalars
  '{:1.0f}%'.format((width/total)*100),
/global/homes/a/acamargo/SCRATCH/.environments/instrain/lib/python3.6/site-packages/inStrain/plottingUtilities.py:762: RuntimeWarning: invalid value encountered in double_scalars
  '{:1.0f}%'.format((width/total)*100),
Plotting plot 7
Failed to make plot #7: 'scaffold'
Skipping plot 8 - you don't have all required information. You need to run inStrain profile_genes first
Skipping plot 9 - you don't have all required information. You need to run inStrain profile_genes first
```

**Comment by apcamargo** [comment]
Indeed, both the coverage and breadth are really low. The log could warn the user about it.

```
scaffold             length  breadth                coverage               median_cov  std_cov            
sample_002_10730542  2432    0.4819078947368421     0.8869243421052632     0           1.1982553439379615 
sample_002_10730671  2043    0.2427802251590798     0.2711698482623593     0           0.5043966770928288 
sample_002_138653    105177  0.0014832140106677315  0.0014832140106677315  0           0.03848394583285722
sample_002_2461827   16948   0.016285107387302336   0.016285107387302336   0           0.1265697541464246 
sample_002_3020790   2586    0.09164733178654293    0.18290796597061101    0           0.5761717715432099 
sample_002_3192508   4513    0.13139818302681144    0.13139818302681144    0           0.33783531568511893
sample_002_3305631   50398   0.005774038652327475   0.005774038652327475   0           0.07576740149938431
sample_002_3491863   2589    0.1096948628814214     0.1096948628814214     0           0.3125090397714081 
sample_002_4122348   3612    0.08361018826135105    0.16528239202657807    0           0.5489157771853571 
sample_002_5889283   47069   0.004057872485075102   0.004057872485075102   0           0.06357205483520234
sample_002_6065399   23149   0.0085100868288047     0.0085100868288047     0           0.09185676486231648
sample_002_6715839   46654   0.00553007244823595    0.00553007244823595    0           0.07415855140813643
sample_002_683206    3324    0.1970517448856799     0.33273164861612514    0           0.7024109239513655 
sample_002_7829595   15093   0.014245014245014244   0.014245014245014244   0           0.11849934098624175
sample_002_8335419   8655    0.028422876949740036   0.028422876949740036   0           0.1661776670182849 
sample_002_8477203   17359   0.013940895212857884   0.013940895212857884   0           0.11724566795204845
sample_002_9169829   13364   0.020577671355881472   0.020577671355881472   0           0.14196559723204352
sample_002_9805083   27646   0.01747088186356073    0.04868697099037835    0           0.3950457927428772 
```

**Comment by michaelwoodworth** [comment]
enjoying working with inStrain so far, having the same issue.  even in low-coverage settings, would be a helpful feature to plot this for comparisons.

thanks!
Mike

`***************************************************
 .:: inStrain profile Step 5. Generate plots ::..
***************************************************
        
making plots 1, 2, 3, 4, 5, 6, 7, 8, 9
Plotting plot 1
Plotting plot 2
Failed to make plot #2: 'scaffold'
Plotting plot 3
Plotting plot 4
/storage/home/hcoda1/0/mwoodworth8/.conda/envs/instrain/lib/python3.6/site-packages/seaborn/distributions.py:2557: FutureWarning: `distplot` is a deprecated function and will be removed in a future version. Please adapt your code to use either `displot` (a figure-level function with similar flexibility) or `histplot` (an axes-level function for histograms).
  warnings.warn(msg, FutureWarning)
Skipping plot 5 - you don't have all required information. You need to run inStrain genome_wide first
Traceback (most recent call last):
  File "/storage/home/hcoda1/0/mwoodworth8/.conda/envs/instrain/lib/python3.6/site-packages/inStrain/plottingUtilities.py", line 1487, in linkage_decay_from_IS
    db = db.sort_values('mm').drop_duplicates(subset=['scaffold', 'position_A', 'position_B'], keep='last')\
  File "/storage/home/hcoda1/0/mwoodworth8/.conda/envs/instrain/lib/python3.6/site-packages/pandas/core/frame.py", line 5298, in sort_values
    k = self._get_label_or_level_values(by, axis=axis)
  File "/storage/home/hcoda1/0/mwoodworth8/.conda/envs/instrain/lib/python3.6/site-packages/pandas/core/generic.py", line 1563, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'mm'
Plotting plot 6
/storage/home/hcoda1/0/mwoodworth8/.conda/envs/instrain/lib/python3.6/site-packages/seaborn/_decorators.py:43: FutureWarning: Pass the following variables as keyword args: x, y. From version 0.12, the only valid positional argument will be `data`, and passing other arguments without an explicit keyword will result in an error or misinterpretation.
  FutureWarning
Plotting plot 7
Failed to make plot #7: 'scaffold'
Skipping plot 8 - you don't have all required information. You need to run inStrain profile_genes first
Plotting plot 9`

`

scaffold | length | coverage | breadth | nucl_diversity
-- | -- | -- | -- | --
FMT03_0000000000001 | 5042869 | 0.30932134 | 0.20922217 | 0.00188399
FMT06_0000000000001 | 4908728 | 3.59698337 | 0.91862658 | 0.00112723

`

**Comment by MrOlm** [comment]
Hello!

inStrain version 1.5.0 has major changes to how the plotting is done, and I believe these issues have now been fixed. Please let me know if the issue persists after upgrading versions.

Best,
Matt
