### ISSUE TITLE
A small error in InStrain Docs

### ISSUE THREAD

**Issue by PandengWang** [MrOlm/inStrain#24]
Thanks so much for this excellent software!

When I read the **Glossary & FAQ** [https://instrain.readthedocs.io/en/latest/overview.html#term-nucleotide-diversity](url), I was confused by the formula of nucleotide diversity. 
![image](https://user-images.githubusercontent.com/48956396/95411160-51dad500-0958-11eb-8260-0ab84bacc473.png)

After I checked the source code, I found the right formula is **1 - [(frequency of A)^2 + (frequency of C)^2 + (frequency of G)^2 + (frequency of T)^2 ]**

**Comment by MrOlm** [comment]
Thank you for finding this and pointing it out to me!! I really appreciate it. Will fix the next time the docs are updated.

Best,
Matt

**Comment by MrOlm** [comment]
Fixed in upcoming docs update
