### ISSUE TITLE
Error installing new version

### ISSUE THREAD

**Issue by icotto25** [MrOlm/inStrain#25]
Hello,

I am trying to get the newest version of inStrain using conda install but I am getting the following error:

UnsatisfiableError: The following specifications were found to be incompatible with each error:
Output in format: Requested package -> Available versions

I also tried to use pip to install it but I got an older version (v1.2.14)

Is there another way to install the newest version?

Thank you,
Irmarie

**Comment by MrOlm** [comment]
Hi Irmarie,

According to PyPi and Bioconda, both are hosting the most up to date version of inStrain (v1.3.9) (https://pypi.org/project/inStrain/) (https://anaconda.org/bioconda/instrain).

I also have trouble with that conda error sometimes, and the only way I'm ever able to fix it is by creating a fresh conda environment and installing it there. PyPi (pip) always works for me with the command `pip install instrain --upgrade` though, so unfortunately I'm not sure how to help with this problem.

Best,
Matt

**Comment by icotto25** [comment]
I was using 'pip install instrain' without the upgrade flag, now I used  'pip install instrain --upgrade' and it worked perfectly. Thank you very much.
