### ISSUE TITLE
TypeError: ufunc 'isnan' 

### ISSUE THREAD

**Issue by icotto25** [MrOlm/inStrain#26]
Hi,

I was running instrain profile (v1.3.9) with 20 samples. Ten of them ran perfectly, however the other 10 got the following error:

TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

The input are sam files.

Do you know why some ran well and some didn't?

**Comment by MrOlm** [comment]
Hello,

Could you provide the log file for one samples that failed?

Thanks,
Matt

**Comment by icotto25** [comment]
Attached is the log file 
[Uploading log.log…]()

**Comment by icotto25** [comment]
Attached is the log file.
[log.log](https://github.com/MrOlm/inStrain/files/5386329/log.log)

**Comment by MrOlm** [comment]
Interesting- this error happened when it was trying to write the output files.

Could you post the 20 lines or so around that error? Also, could you tell me which files ended up in the "output" folder?

Best,
Matt

**Comment by icotto25** [comment]
There are no files in the 'output' folder.

Below is the error:

You gave me a sam- I'm going to make it a .bam now
Converting /scratch/icotto25/shotgun_time_series/clean_reads_univec/inStrain_opera_system/GRE0218_nitrifiers_bins.sam to /scratch/icotto25/shotgun_time_series/clean_reads_univec/inStrain_opera_system/GRE0218_nitrifiers_bins.bam
sorting /scratch/icotto25/shotgun_time_series/clean_reads_univec/inStrain_opera_system/GRE0218_nitrifiers_bins.bam
[bam_sort_core] merging from 48 files and 24 in-memory blocks...
Indexing /scratch/icotto25/shotgun_time_series/clean_reads_univec/inStrain_opera_system/GRE0218_nitrifiers_bins.sorted.bam
***************************************************
    ..:: inStrain profile Step 1. Filter reads ::..
***************************************************
        
Filtering reads: 100%|██████████| 848/848 [00:09<00:00, 91.94it/s] 
10.8% of reads were removed during filtering
892,057 read pairs remain (0.2667 Gbp)
***************************************************
.:: inStrain profile Step 2. Profile scaffolds ::..
***************************************************
        
Profiling splits: 100%|██████████| 91/91 [09:17<00:00,  6.13s/it]  
Merging splits and profiling genes: 100%|██████████| 25/25 [03:25<00:00,  8.22s/it]
Traceback (most recent call last):
  File "/home/icotto25/.conda/envs/py14/bin/inStrain", line 31, in <module>
    inStrain.controller.Controller().main(args)
  File "/home/icotto25/.conda/envs/py14/lib/python3.7/site-packages/inStrain/controller.py", line 49, in main
    self.profile_operation(args)
  File "/home/icotto25/.conda/envs/py14/lib/python3.7/site-packages/inStrain/controller.py", line 75, in profile_operation
    ProfileController(args).main()
  File "/home/icotto25/.conda/envs/py14/lib/python3.7/site-packages/inStrain/controller.py", line 135, in main
    self.run_profile()
  File "/home/icotto25/.conda/envs/py14/lib/python3.7/site-packages/inStrain/controller.py", line 307, in run_profile
    self.write_output()
  File "/home/icotto25/.conda/envs/py14/lib/python3.7/site-packages/inStrain/controller.py", line 319, in write_output
    self.ISP.generate(t)
  File "/home/icotto25/.conda/envs/py14/lib/python3.7/site-packages/inStrain/SNVprofile.py", line 213, in generate
    db = self.get_nonredundant_linkage_table()
  File "/home/icotto25/.conda/envs/py14/lib/python3.7/site-packages/inStrain/SNVprofile.py", line 405, in get_nonredundant_linkage_table
    scdb = self.get('raw_linkage_table')
  File "/home/icotto25/.conda/envs/py14/lib/python3.7/site-packages/inStrain/SNVprofile.py", line 137, in get
    return self._load_pandas(filename)
  File "/home/icotto25/.conda/envs/py14/lib/python3.7/site-packages/inStrain/SNVprofile.py", line 720, in _load_pandas
    return pd.read_csv(location, index_col=0)
  File "/home/icotto25/.conda/envs/py14/lib/python3.7/site-packages/pandas/io/parsers.py", line 686, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/icotto25/.conda/envs/py14/lib/python3.7/site-packages/pandas/io/parsers.py", line 458, in _read
    data = parser.read(nrows)
  File "/home/icotto25/.conda/envs/py14/lib/python3.7/site-packages/pandas/io/parsers.py", line 1196, in read
    ret = self._engine.read(nrows)
  File "/home/icotto25/.conda/envs/py14/lib/python3.7/site-packages/pandas/io/parsers.py", line 2231, in read
    index, names = self._make_index(data, alldata, names)
  File "/home/icotto25/.conda/envs/py14/lib/python3.7/site-packages/pandas/io/parsers.py", line 1677, in _make_index
    index = self._agg_index(index)
  File "/home/icotto25/.conda/envs/py14/lib/python3.7/site-packages/pandas/io/parsers.py", line 1770, in _agg_index
    arr, _ = self._infer_types(arr, col_na_values | col_na_fvalues)
  File "/home/icotto25/.conda/envs/py14/lib/python3.7/site-packages/pandas/io/parsers.py", line 1871, in _infer_types
    mask = algorithms.isin(values, list(na_values))
  File "/home/icotto25/.conda/envs/py14/lib/python3.7/site-packages/pandas/core/algorithms.py", line 443, in isin
    if np.isnan(values).any():
TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

**Comment by MrOlm** [comment]
Interesting. The bug is happening when trying to open an empty file, but it's not clear why it's crashing. It also should have made the "SNVs" and "scaffold_info" output files before crashing? So it's unclear why that didn't happen as well.

Could you try updating pandas (`pip install pandas --upgrade`) and trying again?

-Matt

**Comment by icotto25** [comment]
Hi,

I tried the pandas upgrade and ran instrain profile again but still got the same error. 

Irmarie

**Comment by MrOlm** [comment]
There should be a file named something like `raw_linkage_table` in your `raw_data` folder. Could you send that along please?

**Comment by icotto25** [comment]
Irmarie Cotto has shared a OneDrive for Business file with you. To view it, click the link below.
<https://northeastern-my.sharepoint.com/personal/cotto_i_northeastern_edu/Documents/raw_linkage_table.csv.gz>
[https://r1.res.office365.com/owa/prem/images/dc-generic_20.png]<https://northeastern-my.sharepoint.com/personal/cotto_i_northeastern_edu/Documents/raw_linkage_table.csv.gz>
raw_linkage_table.csv.gz<https://northeastern-my.sharepoint.com/personal/cotto_i_northeastern_edu/Documents/raw_linkage_table.csv.gz>

The file is attached.

Thanks,

Irmarie
________________________________

**Comment by icotto25** [comment]
To view raw_linkage_table.csv.gz, sign in<https://northeastern-my.sharepoint.com/personal/cotto_i_northeastern_edu/_layouts/15/acceptinvite.aspx?invitation=%7B7080F3F3%2D60CB%2D4E75%2D8A3E%2D2D33BF741B21%7D&listId=ca94cc62%2Df537%2D4a6f%2Da2be%2Ddaafd864f3e7&itemId=9e212357%2D00fd%2D48b9%2D9a89%2Db4a3a2cad5c6> or create an account.

**Comment by MrOlm** [comment]
Hello,

I'm unable to view the item and am getting the following errors (screenshot below). I think you should be able to upload it to GitHub directly if you visit the issue page in a web browser and drag the file over.

-Matt

<img width="855" alt="Screen Shot 2020-10-19 at 8 38 49 AM" src="https://user-images.githubusercontent.com/13424205/96473492-9121e500-11e6-11eb-967a-0c4a48b21352.png">
<img width="828" alt="Screen Shot 2020-10-19 at 8 38 01 AM" src="https://user-images.githubusercontent.com/13424205/96473495-91ba7b80-11e6-11eb-8db6-ecc4262c9c5c.png">

**Comment by icotto25** [comment]
I got the message that the file is to big to upload it into the GitHub page. I will try to send it directly to your gmail address.

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by MrOlm** [comment]
Hello,

I figured out the cause of this bug- it is this: https://github.com/pandas-dev/pandas/issues/37094

Using a version of pandas that is not 1.1.3 will fix this issue.

Thanks,
Matt

**Comment by MrOlm** [comment]
`pip install instrain --upgrade` should automatically downgrade pandas to a compatible version without this bug

**Comment by icotto25** [comment]
It worked. Thank you very much.
________________________________
