### ISSUE TITLE
Bio.codonalign.codonalphabet not in biopython 1.78

### ISSUE THREAD

**Issue by bsiranosian** [MrOlm/inStrain#27]
Came across this when doing a fresh install of inStrain via pip. The Bio.codonalign.codonalphabet class is not present in biopython version 1.78 from what I can tell... no mention of it in the docs for that version. 

I was able to install 1.74 via conda, then inStrain functions normally.

**Comment by MrOlm** [comment]
Thanks for the heads up! This is now fixed in the dependency specification of inStrain v1.3.11 (upgrade with `pip install instrain --upgrade`
