### ISSUE TITLE
Gene Histogram Plots Emtpy

### ISSUE THREAD

**Issue by elizabethmcd** [MrOlm/inStrain#29]
I'm using inStrain version 1.3.11 and profiling individual genomes after mapping competitively to the entire assembled set. I first used the profile workflow basically as follows: `inStrain profile POS-2015-07-16-mapping.sorted.bam POS2015-08-06-bin.38.fa -o results/CAPIIB.IS -p 8 -g all-POS-genomes-genes.fna -s POS-genomes.stb` where I prepared the genes and STB files as described in the docs. For this genome, there is ~20X coverage in this sample. From what I can tell pretty much everything works, except I get empty plots in the Gene Histogram output file. 
I initially thought perhaps the profile_genes step in the larger profile workflow didn't work, so I ran `profile_genes` on the IS directory as well. It looks like it just remade some of the raw files for gene level profiling, but none of the figures changed. I've attached the log for the profile and profile_genes runs for this IS directory. I think it's a small thing since from what I can tell everything is working and all the raw data is being produced/calculated correctly, but wanted to check. 
[log.log](https://github.com/MrOlm/inStrain/files/5435602/log.log)

**Comment by MrOlm** [comment]
Hello!

inStrain version 1.5.0 has major changes to how the plotting is done, and I believe these issues have now been fixed. Please let me know if the issue persists after upgrading versions.

Best,
Matt
