### ISSUE TITLE
mutation type missing for intergenic regions

### ISSUE THREAD

**Issue by ecvanderwijk** [MrOlm/inStrain#32]
Hi,
After calling inStrain profile (version 1.4.0), I have this issue which causes some SNVs that are intergenic to have no mutation type annotated as "I". For example, the following output:

scaffold        position        position_coverage       allele_count    ref_base        con_base        var_base        ref_freq        con_freq        var_freq        A       C       T       G       gene    mutation        mutation_typecryptic class
NODE_999_length_47735_cov_45.183958     41629   107     2       C       C       T       0.9439252336448598      0.9439252336448598      0.05607476635514018     0       101     6       0                               True    SNV
NODE_999_length_47735_cov_45.183958     45312   37      2       C       C       T       0.945945945945946       0.945945945945946       0.054054054054054064    0       35      2       0                               True    SNV
NODE_999_length_47735_cov_45.183958     47635   80      2       T       T       G       0.95    0.95    0.05    0       0       76      4                               True    SNV

It is something that can be fixed manually during data analysis, but I was wondering if this also would need fixing in inStrain, or whether something else could be going on, for example with the data?
This is not entirely consistent over 2 similar datasets, and the mutation_type columns are not always identical concerning "I" or empty annotations.
Perhaps another but comparable issue is that in one dataset an annotation from Prodigal is incorporated under the "gene" column, but not in the other dataset.

Best wishes,
Elmar

**Comment by MrOlm** [comment]
Interesting. My guess is that it has something to do with merging tables prior to generating this output. Maybe like if the only SNVs in the sample for a particular scaffold are intergenic this bug happens?

Thank you for reporting the bug- I'll work on it and let you know when a fix is out. I have no reason to believe this bug would impact anything else with the results.

Best,
Matt

**Comment by MrOlm** [comment]
OK I think I've tracked this bug down- can you confirm for me that it only happens on rows where the column "cryptic" is "True"?

**Comment by ecvanderwijk** [comment]
It also seems to happen when "cryptic" is "False", so I hope this does not complicate things more.
But I must note, that sometimes SNPs in one dataset have a "gene", whereas in another it can be empty with also no mutation type.
Thanks for checking this issue! If you have any more questions about the data or output, let me know.

**Comment by MrOlm** [comment]
OK- for a sample where this is happening (especially if "cryptic" is "False"), could you please send the following files present in the `raw_data` folder: `SNP_mutation_types`, `cumulative_snv_table`, as well as the `SNVs.tsv` file in the output folder? Feel free to email me rather than posting here.

Thanks,
-Matt

**Comment by nailabc** [comment]
Hi, I'm facing the same issue where my `SNVs.tsv` output has some rows empty for `mutation_type` and for `gene` as well. I was assuming if there's no gene annotated to that position they should be considered intergenic for `mutation_type`, shouldn't they?

Most of the rows empty for `gene` are classified as intergenic (961 out of 1132), but 171 have empty `mutation_type` (of which one is True for `cryptic` and the other 170 are False). Could you help me figure out why these 171 SNVs are not being classified as any `mutation_type`?

**Comment by MrOlm** [comment]
Hello @nailabc - happy to help. Could you let me know what version of inStrain you're running (should be available in the `log` folder), and what command you used to generate this `SNVs.tsv` file?

**Comment by nailabc** [comment]
Sure, thanks for helping! I used inStrain version 1.5.7 (installed in a python v3.8.10 environment) and the command I used to generate the `SNV.tsv` file was:
`inStrain profile sample.bam ref_sample.fa -o IS_sample -g genecalls_sample.fna -p 16 --min_mapq 13 --min_freq 0`

**Comment by MrOlm** [comment]
OK thanks. Could it that SNVs on scaffolds with no genes called are lacking this information? That is, is this information only missing for certain scaffolds?

If not, would you mind sending the log file (in the log folder) and the SNVs.tsv file? You can send to my personal email (mattolm@stanford.edu) if you'd rather not post publicly.

Thanks,
MO

**Comment by nailabc** [comment]
I don't think I have scaffolds with no genes called, analysing it deeper now I can see that some positions that are empty for mutation type and gene should be in the middle of a gene. I'm gonna send you the files with this example of a position within a gene but with an empty mutation type. Thanks a lot for your help!

**Comment by 473021677** [comment]
Hi,
I have the same issue. I do not know why these pisitions within a gene but with an empty mutation type were generated and need your help. Thanks in advance.

Best regards,
Yang Yuan

**Comment by MrOlm** [comment]
They are either crypic mutations or have more than 2 alleles present

**Comment by 473021677** [comment]
So&nbsp;if&nbsp;I&nbsp;want&nbsp;to&nbsp;calculate&nbsp;the&nbsp;average&nbsp;major&nbsp;allele&nbsp;frequency&nbsp;for&nbsp;the&nbsp;genes,&nbsp;these&nbsp;positions&nbsp;within&nbsp;the&nbsp;genes&nbsp;without&nbsp;mutation&nbsp;type&nbsp;should&nbsp;not&nbsp;be&nbsp;included?
----&nbsp;原始邮件&nbsp;----
***@***.***&gt;;
Date:2024年12月25日(星期三)&nbsp;晚上10:41
***@***.***&gt;;
***@***.******@***.***&gt;;
Subject:Re:&nbsp;[MrOlm/inStrain]&nbsp;mutation&nbsp;type&nbsp;missing&nbsp;for&nbsp;intergenic&nbsp;regions&nbsp;(#32)



 
They are either crypic mutations or have more than 2 alleles present
 
&mdash;

**Comment by 473021677** [comment]
Thanks for your explanation. I have another question, If I want to calculate the average major allele frequency for the genes, should I ignore these positions within a gene but with an empty mutation type?

Best regards,
Yang Yuan

**Comment by MrOlm** [comment]
I would ignore the ones where cryptic=true, but keep the ones where the number of alleles is over 2On Dec 25, 2024, at 6:49 PM, 473021677 ***@***.***> wrote:﻿
Thanks for your explanation. I have another question. If I want to calculate the average major allele frequency for the genes, should I ignore these positions within a gene but with an empty mutation type?
Best regards,
Yang Yuan

**Comment by 473021677** [comment]
Can I ignore the positions where the number of alleles is over 2?
