### ISSUE TITLE
AssertionError Could not load the scaffold to bin file!

### ISSUE THREAD

**Issue by michaelwoodworth** [MrOlm/inStrain#34]
Hi, thanks so much for your effort in developing and maintaining inStrain, it's incredibly useful.

I'm running inStrain v 1.4.0 installed with conda.

I am using two bacterial genomes as references and running profile across multiple metagenomes mapped to these references with bowtie2.  I'm supplying a sorted bam, the prodigal nucleotide file, (concatenated) reference genomes, and and reference scaffolds but getting this AssertionError with some (but not all) of inStrain profile analyses.

Is there an obvious reason why neither -s argument method would work for a subset of metagenome analyses? I recognize this is somewhat similar to [#15](https://github.com/MrOlm/inStrain/issues/15) but not exactly.

thanks!
Mike

```console
## RUN submitting space-separated scaffold list
inStrain profile ${bam_dir}/${ID}.sorted.bam ${cat_dir}/PM04_derep_Ecoli_isolate_genomes.fasta -o ${outdir}/${ID}_PM04-derep-isolate-genomes.IS -p 20 -g ${cat_dir}/PM04_derep_Ecoli_isolate_genomes.fna -s ${f_dir}/p20105-s030_scaffolds.fasta  ${f_dir}/p20105-s034_scaffolds.fasta

## RUN submitting scaffold2bin.json file (pointing to successful profile run) instead of space-separated scaffold list
inStrain profile ${bam_dir}/${ID}.sorted.bam ${cat_dir}/PM04_derep_Ecoli_isolate_genomes.fasta -o ${outdir}/${ID}_PM04-derep-isolate-genomes.IS -p 20 -g ${cat_dir}/PM04_derep_Ecoli_isolate_genomes.fna -s ${stb_dir}/scaffold2bin.json


############# Identical Assertion errors below

***************************************************
    ..:: inStrain profile Step 1. Filter reads ::..
***************************************************
        
Filtering reads: 100%|█████████████████████████████████████████████████████████████████████████████████████████| 377/377 [00:04<00:00, 77.89it/s]
15.7% of reads were removed during filtering
68,100 read pairs remain (0.02590 Gbp)
***************************************************
.:: inStrain profile Step 2. Profile scaffolds ::..
***************************************************
        
Profiling splits: 100%|██████████████████████████████████████████████████████████████████████████████████████████| 21/21 [00:25<00:00,  1.20s/it]
Merging splits and profiling genes: 100%|████████████████████████████████████████████████████████████████████████| 20/20 [01:57<00:00,  5.86s/it]
***************************************************
.:: inStrain profile Step 4. Make genome-wide ::..
***************************************************
        
Could not load the scaffold to bin file!
Traceback (most recent call last):
  File "/storage/home/hcoda1/0/mwoodworth8/.conda/envs/instrain/bin/inStrain", line 31, in <module>
    inStrain.controller.Controller().main(args)
  File "/storage/home/hcoda1/0/mwoodworth8/.conda/envs/instrain/lib/python3.6/site-packages/inStrain/controller.py", line 50, in main
    self.profile_operation(args)
  File "/storage/home/hcoda1/0/mwoodworth8/.conda/envs/instrain/lib/python3.6/site-packages/inStrain/controller.py", line 76, in profile_operation
    ProfileController(args).main()
  File "/storage/home/hcoda1/0/mwoodworth8/.conda/envs/instrain/lib/python3.6/site-packages/inStrain/controller.py", line 142, in main
    self.profile_genome_wide()
  File "/storage/home/hcoda1/0/mwoodworth8/.conda/envs/instrain/lib/python3.6/site-packages/inStrain/controller.py", line 356, in profile_genome_wide
    Controller().genome_wide_operation(copy.deepcopy(args))
  File "/storage/home/hcoda1/0/mwoodworth8/.conda/envs/instrain/lib/python3.6/site-packages/inStrain/controller.py", line 88, in genome_wide_operation
    inStrain.genomeUtilities.Controller().main(args)
  File "/storage/home/hcoda1/0/mwoodworth8/.conda/envs/instrain/lib/python3.6/site-packages/inStrain/genomeUtilities.py", line 40, in main
    self.prepare_genome_wide(IS, vargs)
  File "/storage/home/hcoda1/0/mwoodworth8/.conda/envs/instrain/lib/python3.6/site-packages/inStrain/genomeUtilities.py", line 127, in prepare_genome_wide
    stb = load_scaff2bin(vargs.get('stb'), IS)
  File "/storage/home/hcoda1/0/mwoodworth8/.conda/envs/instrain/lib/python3.6/site-packages/inStrain/genomeUtilities.py", line 875, in load_scaff2bin
    assert False
AssertionError
```

**Comment by MrOlm** [comment]
Hi Mike,

Thanks for the kind words and detailed bug report. 

First, while inStrain does store the .stb file as a .json file, it can't read them that way from the command line. So it makes sense why the second command doesn't work.

The first command you have, with a space-separated list of genomes, should work though. That's very weird that it works on some runs but not others. Just to be clear, you're providing the same list of genomes to every run, or a different list to every run? Also, these are regular .fasta files with sequences still there, yes? I only ask because your comment says "space-separated scaffold list", but it should be "space-separated genome list".

For troubleshooting, it would be helpful to have the log file for a run that worked and a run that didn't work (`log/logging.log`). Feel free to email rather than post here if you'd prefer.

A potential workaround would be to use the `parse_stb.py` script, provided in the package `dRep`. That will convert your list of genomes into a tab-separated .stb file, which can be provided to the `-s` argument. 

Thanks again,
Matt

**Comment by michaelwoodworth** [comment]
Thanks for the quick response Matt. Yes, it’s the same 2 reference isolate genomes (as regular .fasta files) across metagenomes and submitted as a space-separated genome list.  I thought the .json attempt would be a long shot!

I’ll email the logs separately and try the parse_stb.py as a workaround in parallel.

thanks!

Mike

**Comment by michaelwoodworth** [comment]
Issue was resolved. Thanks again for the support.
