### ISSUE TITLE
samtools view not multithreaded

### ISSUE THREAD

**Issue by ramiroricardo** [MrOlm/inStrain#35]
Hi Matt,

I realized that when converting `sam` to `bam`, inStrain is using `samtools view` with a single thread. Is there a specific reason for this? just wondering if it could speed this step a little by adding more threads.

Best,

Ramiro

**Comment by MrOlm** [comment]
Hi Ramiro - thanks for pointing this out to me. There's no reason for it, and I'll fix it in the next inStrain point release.

Best,
Matt

**Comment by MrOlm** [comment]
Fixed in version 1.5.1, released today. Upgrade with `pip install instrain --upgrade`
