### ISSUE TITLE
inStrain compare fails at Step3

### ISSUE THREAD

**Issue by y-hwang** [MrOlm/inStrain#36]
Hello, thank you for creating a great tool! I get this error when running inStrain compare with three input objects. Could you help me figure out what the issue is?
***************************************************
..:: inStrain compare Step 3. Auxiliary processing ::..
***************************************************
                
Could not cluster genomes; heres a traceback:
Traceback (most recent call last):
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/site-packages/inStrain/compare_controller.py", line 356, in run_genome_clustering
    Cdb = inStrain.compare_utils.cluster_genome_strains(Mdb, kwargs)
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/site-packages/inStrain/compare_utils.py", line 212, in cluster_genome_strains
    arr = scipy.spatial.distance.squareform(arr, checks=True)
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/site-packages/scipy/spatial/distance.py", line 2215, in squareform
    is_valid_dm(X, throw=True, name='X')
  File "/n/home12/yhwang/.conda/envs/instrain/lib/python3.8/site-packages/scipy/spatial/distance.py", line 2290, in is_valid_dm
    raise ValueError(('Distance matrix \'%s\' must be '
ValueError: Distance matrix 'X' must be symmetric.

**Comment by MrOlm** [comment]
Hello,

This error usually happens when the job runs our of RAM and silently crashes. It is possible to re-run the job with more RAM? If not, can I ask how many inStrain profile objects you're running the job on?

Best,
Matt

**Comment by y-hwang** [comment]
Thanks for the suggestion, I ran it this time with only two objects and more RAM and step 3 worked! But I get another error in step 4 for plotting plot 10. Failed to make plot #10: Distance matrix 'X' must be symmetric.

**Comment by MrOlm** [comment]
Interesting- that's strange that the distance matrix works on one setting and not the other. 

Would you mind providing me with a couple of files so that I can troubleshoot this issue? I could use the files `log/logger.log`, `raw_data/comparisonTable`, `raw_data/scaffold2bin`, and `raw_data/bin2length`.

Feel free to upload here or email to me.

Thanks,
Matt

**Comment by MrOlm** [comment]
Fixed in version 1.5.1, released today. Upgrade with `pip install instrain --upgrade`
