### ISSUE TITLE
Is coverage breadth for MAG the mean method in CoverM

### ISSUE THREAD

**Issue by jianshu93** [MrOlm/inStrain#37]
Hello Matt,

I am writing to ask whether the coverage breadth option is the CoverM genome mean option (total position mapped by reads for at least one time divided by length minus 2*75 bp for each contig in the genome)

Thank you,

Jianshu

**Comment by MrOlm** [comment]
Hello,

Can you clarify what you mean by the "coverage breadth option"?

Thanks,
Matt

**Comment by MrOlm** [comment]
Do you mean breadth as reported in output files?

**Comment by jianshu93** [comment]
yes. coverage breadth of a MAG. calling coverm as introduced in the tutorial.

**Comment by MrOlm** [comment]
Hello,

If running `quick_profile`, breadth is the value "covered_bases" reported by coverM (https://github.com/wwood/CoverM)

Best,
Matt
