### ISSUE TITLE
minimap2 instead of bowtie2?

### ISSUE THREAD

**Issue by nick-youngblut** [MrOlm/inStrain#42]
This is a question versus an issue: do you think that minimap2 could be used instead of bowtie2? minimap2 is 2-3X faster than bowtie2, so it would be nice to use it, if possible. You have done any testing comparing the mappers to see if it affects the inStrain results?

**Comment by MrOlm** [comment]
I have not tested minimap2, but please let me know if you do. If it works I'll add it to a list of mapping software that works (https://instrain.readthedocs.io/en/latest/overview.html#what-mapping-software-can-be-used-to-generate-bam-files-for-instrain)

Some things to keep in mind are 1) some mapping software modifies .fasta file headers during mapping; if  minimap2 does this you'll need to add the `--use_full_fasta_header` flag. 2) By default inStrain requires all reads to be paired. If that's not the case, read filtering flags will need to be adjusted accordingly

**Comment by MrOlm** [comment]
I'm going to close this issue for now, but please let me know if you have success with minimap2 and I'll add it to the docs as a "working" mapping software
