### ISSUE TITLE
Question: estimating relative abundace

### ISSUE THREAD

**Issue by smb20200615** [MrOlm/inStrain#43]
Hello,

I was wondering how I could get relative abundance of strains from the genome_wide output. Would that be from the breadth? Also, instead of using dRep, would it be possible to use the pangenome reference that is outputted by tools such as panaroo or roary as the reference database? Also my last question is that sometimes iRep is blank, do you have any guidance on why that is?

Best wishes,

**Comment by MrOlm** [comment]
Hello,

At the moment you can just compare the relative abundance of the populations between samples. Say strain A, based on genome X, is in samples 1 and 2. You now know that genome X is the same strain in both samples, so you could compare the relative abundance of genome X in samples 1 and 2. But if multiple strains are present within genome X, there’s no way to phase them out. InStrain compare isn’t really phasing out multiple strains in a sample, it’s just seeing if there is micro-diversity overlap between samples. Conceptually inStrain operates on the idea of “strain clouds” more than distinct strains. InStrain isn’t able to tell the *number* of strains that are shared between two samples either, just that there is population-level overlap for some particular genome. Doing haplotype phasing is something we’ve considered and may add in the future, but the feature won’t be coming any time in the near future. Sorry for the confusing explanation- let me know if I can clarify anything.

I like the idea of mapping to a pangenome, but I haven't tested it. My main concern is that you'd end up with very short contains to map reads to, which reduced read map-ability.

iRep is a weird metric in that it has a lot of quality checks it does, and if any of those checks fail it doesn't generate an iRep value. If you search the log for a particular genome that doesn't have an iRep value, you should find the iRep check(s) that failed for that particular genome

Best,
Matt

**Comment by smb20200615** [comment]
Thank you for the quick and thorough reply. And the relative abundance is based on breadth?

**Comment by smb20200615** [comment]
Thank you!

**Comment by earlylifemicro-lab** [comment]
Hi Matt,
May I further ask whether the relative abundance of genes in gene_info.tsv could be calculated, based on the relative abunance of genomes from genome_info.tsv?
Thank you very much.
Best,
Wang
