### ISSUE TITLE
position in gene for reverse strand

### ISSUE THREAD

**Issue by ecvanderwijk** [MrOlm/inStrain#44]
Hi there, I might have another issue. For the SNV output table, I also tried to manually calculate the position of the SNP in the gene it is located in, and I compared it to the position provided by the "mutation" row, and I noticed something.

For inStrain, the calculations are done as followed I think? Please correct me if I'm wrong, I'd very much like to learn:
1. SNV position in the contig, from the SNV file, is 0-based
2. The 1-based and inclusive Prodigal start and end positions are converted to 0-based positions.
3. The SNV position within the gene is calculated as [SNV position within contig] - [0-based start position]

So, for example, a SNV at position 8067 is at position 0 in the gene if the 1-based Prodigal gene starts at position 8068 (in the Prodigal file)
A SNV at position 9067 is at position 1000 in the gene if the Prodigal gene starts at position 8068 and goes until 9068.
A SNV at position 9068 will not be in the gene.

And now for my question:
A gene can be on the (+)-strand or (-)-strand (1 or -1 in the Prodigal genes.fna file).
Currently, the SNV position in the gene is calculated in the same way for both, namely as described above, and counting from the 0-based start position.
However, should the SNV position on the (-)-strand not be calculated with respect to the end position?
For example:
A SNV at position 234 will be at position 111 if the Prodigal gene end positions (which is really the start position of the gene) is at 345.

I am also wondering whether this has implications for the determination of the N or S annotations for "mutation" and "mutation_type"?

I hope you could take a look at this issue.

Best wishes,
Elmar

**Comment by MrOlm** [comment]
Hi Elmar,

Thanks for reaching out with the question and concern. 

Calculation of mutation type and intergenic location is done in the method "characterize_SNPs" in the the file "GeneProfile.py" (https://github.com/MrOlm/inStrain/blob/97d6cf45242c462bec22adcd9645745aa3b31d79/inStrain/GeneProfile.py). 

I follow most of your explanation, but am confused by the sentence "A SNV at position 234 will be at position 111 if the Prodigal gene end positions (which is really the start position of the gene) is at 345". Can you explain?

I think I understand the confusion though. The position reported in the column "mutation" is reported with respect to the "start" of the gene, where "start" is defined without consideration of gene direction. I see why that is confusing. I will add a note of this to the documentation and consider changing this behavior in future versions of inStrain. You're right that most people would expect the "mutation" to be with respect to gene directionality.

The mutation_type (N, S, etc.) is calculated in a way that's robust to this, however. It's kind of silly, but the way that it's calculated is by translating the gene with and without the SNP. If the direction of the gene is (-1), the reverse compliment of the gene is used when searching for amino acid differences. As far as my tests show me,  "mutation_type" is reported correctly and is robust to gene direction. **Please let me know if you have any examples where it is not calculated correctly.**

Best,
Matt

**Comment by ecvanderwijk** [comment]
Hi Matt,

Thank you for your swift response.
I now also see that that sentence was formulated in a rather unfortunate manner. What I meant to say is that one would expect for the (-)-strand the position in the gene to be the [sequence end as reported in the Prodigal file] - [position]. So, for example: if a SNP occurs at position 234 with respect to the contig, with the gene direction being (-), then one would expect the relative position in the gene to be 345 (the end of the gene) - 234 = 111.
But of course this does not matter if inStrain is consistent in its calculations and determination of the effect of the mutation, like you described.

Thank you for taking away my concerns. But I agree that a note in the documentation would be helpful to others.

Best wishes,
Elmar

**Comment by MrOlm** [comment]
Note has been added to the docs as of today

**Comment by ramiroricardo** [comment]
Hi all,

sorry to reopen this, but I was also struggling for a while to understand the output of the mutation column. I think I now understood that the position is not the amino acid position, but the nucleotide position. Is this right?

**Comment by MrOlm** [comment]
Hello,

Sorry for the confusing notation- I am working on changing it.

The position is the nucleotide position, and it goes from 5' to 3' no matter the true direction of the gene.

Please let me know if I can answer any more questions

-Matt
