### ISSUE TITLE
Question about using instrain to compare metagenomes

### ISSUE THREAD

**Issue by smb20200615** [MrOlm/inStrain#45]
Hello,

I was following your tutorial for MAGs and wanted to use MAGs to assess similarity of two metagenomes. I ran dRep compare and have subsetted the comparisons to those with popANI greater than 99.99% and percent bases compared of at least 0.5. Would I compare the absolute number of "same strains" to determine which metagenomes are similar or calculate the proportion of "same strains" over all strain level comparisons between the two samples. I am not sure if we can get a reliable denominator. Any other guidance you would have on showing the similarity between metagenomes using output from inStrain on a MAG catalogue such as that generated by Almeida et al would be appreciated.

Best wishes,

**Comment by MrOlm** [comment]
Hello,

Great question. I don't know if there's a "right" answer but I can tell you what I've done. For the denominator I've used the total number of strains (based on the file `strain_clusters.tsv`  https://instrain.readthedocs.io/en/latest/example_output.html#strain-clusters-tsv).

The theoretical framework is that each genome detected in a sample is a strain, and if two genomes share >99.99% ANI they're the same strain. Doing this lets you calculate a number of distance metrics between samples. The one that I've found most useful is Jaccard similarity (number of shared strains / number of total strains).

Below is some python code I've used to calculate metagenome similarily based on strain-shared, all based on sets. Let me know if you have any questions.

Best,
Matt

```
Tdb = pd.read_csv('DeltaI_ClusterInfo_v6.csv')
Tdb['strain'] = Tdb['cluster']
table = defaultdict(list)
for i, idb in Tdb.groupby('sample'):
    iset = set(idb['strain'].tolist())
    for j, jdb in Tdb.groupby('sample'):
        jset = set(jdb['strain'].tolist())

        table['sample1'].append(i)
        table['sample2'].append(j)
        table['intersection'].append(len(iset.intersection(jset)))
        table['union'].append(len(iset.union(jset)))
        table['percent_shared'].append(len(iset.intersection(jset)) / len(iset.union(jset)))
        table['min_shared'].append(len(iset.intersection(jset)) / min(len(jset), len(iset)))
        table['Jaccard'].append(len(iset.intersection(jset)) / len(iset.union(jset)))
        table['1_shared'].append(len(iset.intersection(jset)) / len(iset))

SHRdb = pd.DataFrame(table)
assert len(Tdb['sample'].unique()) * len(Tdb['sample'].unique()) == len(SHRdb)
```

**Comment by smb20200615** [comment]
Thank you so much for your swift response and thorough explanation as always!
