### ISSUE TITLE
building RG fasta file; only certain microbes of interest

### ISSUE THREAD

**Issue by NienkeMekkes** [MrOlm/inStrain#46]
Dear authors,

Many thanks for creating inStrain, and the very thorough documentation that goes with it. I finished the tutorial, and now want to use it on some of our own samples.

In my case, I have metagenomic samples from very different environments (think from complex soil, to more simple dairy samples). So I expect to find many, many different microbes. I also have a set of target microbial genomes (includes multiple strains for some species) that I am interested in and trying to find in all those environments. I can think of the following ways to use inStrain:

1. build a very, very big RG fasta file, with many genomes of commonly occuring microbes and my microbes of interest, and run instrain as usual
2. like above, build a very big .fasta file that is used to create the .bam file. And then pass a .fasta file for only my genomes of particular interest.
3. build a RG fasta file of only my genomes of interest. this has a higher risk of mismapping, which I maybe can counter by using the options as explained in the tutorial.
4. go for the probably more time consuming option of de novo assembly before running instrain

Would you be able to give me guidance on if these options make sense, and if you have an idea on which one would be the best approach?

Kind regards

**Comment by MrOlm** [comment]
Hello,

Thanks for the kind words and good question. If I were you in your position I would do option 1, but there are a couple of things to keep in mind. 

1) Make sure you de-replicate your genomes before combining them all. If you have lots of similar genomes they'll all steal reads from each other. See https://instrain.readthedocs.io/en/latest/important_concepts.html#establishing-and-evaluating-genome-databases for more info. 

2) Option 2 isn't necessary if you run inStrain with `--database_mode`. With that option the first thing inStrain will do is quickly check which genomes have at least some minimum number of reads mapped to them, and only those genomes will be processed for downstream analysis. This process is pretty computationally simple and efficient, so there's no real cost to doing things this way. 

3) The main benefit of option (1) is simplicity (which is a really big benefit in my mind!), and the main drawback is the complexity of mapping with bowtie2. You'll probably need to build a "large" bowtie2 index, and mapping to 10,000 genomes takes a lot longer than mapping to 100 genomes (but mapping to 10,000 genomes is still not too bad). Once you have a .bam file,  the only thing that matters computationally for inStrain is the size of the .bam file (a .bam file mapped to 10,000 genomes will take a similar amount of time to process as a .bam file mapped to 10 genomes, assuming there are the same number of reads mapped to each).

4) Once you've finished option 1, check out the percentage of reads that map to your RG fasta file. If a low percentage of reads are mapping, you may want do go with option (4) and de novo assemble sample-specific genomes if you can.

Best,
Matt

**Comment by MrOlm** [comment]
I'm closing this but let me know if you have any other questions
