### ISSUE TITLE
Distance matrix 'X' must be symmetric

### ISSUE THREAD

**Issue by SergioRLL** [MrOlm/inStrain#47]
Hello,

I have run `inStrain compare` and I have got this error in these steps:

..:: inStrain compare Step 3. Auxiliary processing ::..

Could not cluster genomes; heres a traceback:
Traceback (most recent call last):
  File "/home/srodriguez/.local/lib/python3.8/site-packages/inStrain/compare_controller.py", line 356, in run_genome_clustering
    Cdb = inStrain.compare_utils.cluster_genome_strains(Mdb, kwargs)
  File "/home/srodriguez/.local/lib/python3.8/site-packages/inStrain/compare_utils.py", line 212, in cluster_genome_strains
    arr = scipy.spatial.distance.squareform(arr, checks=True)
  File "/opt/ohpc/pub/apps/python/3.8.5/lib/python3.8/site-packages/scipy/spatial/distance.py", line 2184, in squareform
    is_valid_dm(X, throw=True, name='X')
  File "/opt/ohpc/pub/apps/python/3.8.5/lib/python3.8/site-packages/scipy/spatial/distance.py", line 2259, in is_valid_dm
    raise ValueError(('Distance matrix \'%s\' must be '
ValueError: Distance matrix 'X' must be symmetric.

..:: inStrain compare Step 4. Store results ::..

making plots 10
Plotting plot 10
Failed to make plot #10: Distance matrix 'X' must be symmetric.

Any ideas of why this is happening?
Thank you,

Sergio

**Comment by MrOlm** [comment]
Hi Sergio,

May I ask what version of inStrain you're running? It will show near the top of your run `inStrain -h`. I tried to fix this bug in version `1.5.1` which was only recently released.

Best,
Matt

**Comment by SergioRLL** [comment]
Hi, 

I was indeed using a previous version (1.4.1). I installed version 1.5.1 and the log reports a warning that the inStrain folder is from version 1.4.1 while the program version is in 1.5.1. Then it cannot cluster the genomes, is it because the profiles that I'm using were generated with version 1.4.1?

Thanks again,
Sergio

**Comment by MrOlm** [comment]
Hi Sergio,

Version 1.5.1 should be able to work with profiles generated with a pervious version. Can you send me the log file so I can see what's happening? (`log/log.log`) Feel free to email instead of posting here if you'd prefer.

Best,
Matt

**Comment by SergioRLL** [comment]
Hi,

I sent you the log file via email.

Sergio

**Comment by SergioRLL** [comment]
Thank you, that worked well! I was wondering if is there may be an issue if the profiles were generated without the `--database_mode` when doing `inStrain profile`.

Regards,
Sergio

**Comment by MrOlm** [comment]
Hi Sergio,

Nope, generating profiles without `--database_mode` won't be a problem. For `profile`, `--database_mode` just make things run faster.

Best,
Matt
