### ISSUE TITLE
Is it possible to know the species/strain name

### ISSUE THREAD

**Issue by Biofarmer** [MrOlm/inStrain#50]
Hi Dr. Olm,

1. It is very nice to read and understand you newest tool inStrain. I have run it on some of my samples, and one question in my mind right now is whether it is possible to know the strain names that are shared across the samples found by inStrain?
2. If not running quick_profile, it does not matter whether CoverM is installed or not,  right? When I run inStrain profile, I found the CoverM is not passed.
```coverm........................ ! NOT WORKING ! (version=na) (location = None)```

Thanks,
Wang

**Comment by MrOlm** [comment]
Hello,

1) InStrain doesn't have a taxonomy component to it at the moment. You can figure out the taxonomy of the genome the strain in based on using a tool like GTDB, but there's no way to get more specific taxonomy of particular strains. When you cluster samples with inStrain compare, you'll get a cluster name for each strain cluster. The cluster name is usually what I use for my "strain" name.

2) That's correct- coverM is only needed for quick_profile.

Best,
Matt

**Comment by Biofarmer** [comment]
Many thanks, it makes sense to me.

**Comment by Biofarmer** [comment]
Hi Matt,

1. May I ask whether the diversity of strains within one species can be obtained with inStrain? For example, if I have two samples with species A, and there may be different strains in species A from each sample. So I am curious whether inStrain can do it, and further compare strains between samples?
2. This is unrelated to the question 1. I have the results from inStrain profile for several samples, in the next step I want to run inStrain compare, so I just list all the IS folder as below (omitting the other flags here):
```
inStrain compare -i profile1 profile2 profile3 profile4
```
Or I can also put all the profile folders in one directory and run:
 ```
inStrain compare -i where/the/all/profile/* 
```
Am I correct?
Many thanks
Wang

**Comment by MrOlm** [comment]
Hello,

1. `InStrain compare` is the only way of comparing a genome detected in multiple samples (e.g. species A). It will tell you how similar the populations of species A are in the two samples, and you can set a similarity threshold for classifying the strains as same or different. A threshold I like it 99.999% popANI
2. It just depends on if you can get the wildcard to be properly expanded. A way to test this is to run  `ls where/the/all/profiles/*`. That will show you what will be sent to inStrain. If running `ls where/the/all/profiles/*` just shows the locations of all of the folders, it will work when passed to inStrian as well.

-Matt

**Comment by Biofarmer** [comment]
Hi Matt,

Many thanks.

Wang

**Comment by Biofarmer** [comment]
Hi Matt,

I have a question regarding the presence or absence of organism in a sample. You mentioned "We recommend using a 50% **breadth** threshold to determine presence/absence instead." I think the **breadth** here refers to the column of **breadth** in the genome_info.tsv, right? However, when running _inStrain compare_, the flag **--breadth** is saying "Minimum **breadth_minCov** required to count a genome present (default: 0.5)". As I understand, **breadth** and **breadth_minCov** refer to different columns in genome_info.tsv. Do I understand correctly? If yes, may I ask the reason why breadth_minCov is used for _inStrain compare_, not **breadth**?

Many thanks
Wang

**Comment by MrOlm** [comment]
Great question- you are correct in everything.

The reason breadth_minCov is use for compare has to do with the ability to detect SNPs. To compare samples with inStrain compare, you want to make sure you have an idea of the alleles present in each sample. 5x coverage is the minimum coverage needed to detect the presence of two alleles. So only the regions of the genome with 5x coverage are compared with inStrain compare, and breadth_minCov is the percent of the genome that has at least 5x coverage.

When you just want to detect a genome, it doesn't matter what alleles are present, so 1x coverage is fine (breadth is the percent of the genome with at least 1x coverage)

-Matt

**Comment by Biofarmer** [comment]
Hi Matt,

Many thanks for reply, which makes sense to me. In a paper you co-authored https://www.biorxiv.org/content/10.1101/2021.01.26.428340v1, it wrote "These 274 subspecies comprise 560 distinct strains,...". As I understand, the subspecies refer to the genomes after dRep, which is used for inStrain profile, and the detected genomes will be outputted in genome_info.tsv. Personally, one genome stands for one strain, right? Why are there 560 distinct strains from 274 subspecies?

Best,
Wang

**Comment by MrOlm** [comment]
Hi Wang, 

In that case, each genome was a sub-species. Strains were groups of genomes with >= 99.999% popANI (as output in `strain_clusters.tsv` from `inStrain compare`)

-Matt

**Comment by Biofarmer** [comment]
Hi Matt,

Oh... so for example as below, genome_1.fna is a subspecies, but with 4 clusters from _inStrain compare_, so it means genome_1.fna contains 4 distinct strains, am I right?
```
cluster | sample | genome
-- | -- | --
1_1 | sample1.bam | genome_1.fna
1_1 | sample2.bam | genome_1.fna
1_10 | sample3.bam | genome_1.fna
1_11 | sample4.bam | genome_1.fna
1_12 | sample5.bam | genome_1.fna
```
Thanks
Wang

**Comment by MrOlm** [comment]
Yes, that's exactly correct

**Comment by Biofarmer** [comment]
Okay, that's great. Thanks.

**Comment by Biofarmer** [comment]
Hi Matt, 

Sorry to bother you again. I just read the options for GENOME CLUSTERING, and -cov COVERAGE_TRESHOLD with default is 0.1, may I ask whether I need to change it to 0.5 when following your suggestion "We recommend using a 50% breadth threshold to determine presence/absence instead"?

Thanks
Wang

**Comment by MrOlm** [comment]
If you have deep sequencing I would recommend setting it to 0.5, but if some of your samples have somewhat shallow sequencing, I would keep it at the 0.1. 0.1 is much more amenable to low abundance genomes.

-Matt

**Comment by Biofarmer** [comment]
Hi Matt,

Thanks for reply. I want to explain more about my question, which may make you confused. I want to ask as you mentioned 'using a 50% breadth threshold to determine presence/absence instead' or 'breadth_minCov with 0.5', why when clustering, the COVERAGE_TRESHOLD (percent_genome_compared) for a genome comparison to count is set to 0.1, not 0.5?

Thanks 
Wang

**Comment by Biofarmer** [comment]
Hi Matt,

As for the abundance, I just found it here https://github.com/MrOlm/inStrain/issues/43. As I understand, in the genome_info.tsv, each genome should be unique, and represents the single or multiple strains of this genome, right? You said we can compare the abundance if only single strain in this genome, but my further question is how we know whether each genome in genome_info.tsv represents single or multiple strains in that sample? In the paper https://www.biorxiv.org/content/10.1101/2021.01.26.428340v1, there is indeed relative abundance reported, but not clear how to get it.

Thanks
Wang

**Comment by MrOlm** [comment]
Hi Wang,

In that paper, the abundance of the strain was simply the abundance of the genome in that sample. There's no way to separate out the abundance of different samples in the sample. If subspecies (genome) X is in samples 1 and 2, and sample 1 has strain A of genome X and samples 2 has strain B of genome X, the abundance of A in sample 1 is simply the abundance of genome X in that sample, and the abundance of strain B in sample 2 is the abundance of genome X in sample 2.

Best,
Matt

**Comment by Biofarmer** [comment]
Hi Matt,

Oh...thanks. It makes sense to me. I am getting more and more knowledge of inStrain.
May I have your view on the issue I asked previously when you are available:
As it is mentioned 'using a 50% breadth threshold to determine presence/absence instead' or 'breadth_minCov with 0.5', why when clustering, the COVERAGE_TRESHOLD (percent_genome_compared) for a genome comparison to count is set to 0.1, not 0.5?

Thanks
Wang

**Comment by MrOlm** [comment]
Hello,

There's no set answer to that question. COVERAGE_TRESHOLD is like minimum alignment coverage in dRep (https://drep.readthedocs.io/en/latest/choosing_parameters.html#minimum-alignment-coverage).

 If you compare two genomes with 50% breadth_minCov, assuming they're each 50% across random parts of the genome, you'd expect percent_genome_compared to be 0.25 (0.5 * 0.5). So 0.25 could be an OK minimum as well? It's really kind of up to you and how stringent you want to be. 

If you have deep sequencing (and thus high breadth_minCov), you could set it to 0.5, but if some of your samples have somewhat shallow sequencing (and thus low breadth_minCov), I would keep it at the 0.1. 0.1 is much more amenable to low abundance genomes (with low breadth_minCov).

-Matt

**Comment by Biofarmer** [comment]
Hi Matt, thank you very much for reply. Best, Wang

**Comment by Biofarmer** [comment]
Hi Matt,

I noticed that in the Figure 3A of paper https://www.biorxiv.org/content/10.1101/2021.01.26.428340v1, there are some species name with sp1, sp2 and sp3. I understand this is due to the same taxa assignment (by tRep and GTDB) to different subspecies clustered by dRep, do I understand correctly?

Thanks
Wang

**Comment by Biofarmer** [comment]
Hi Matt,

May I have your reply when you are available? Many thanks.

Best,
Wang

**Comment by MrOlm** [comment]
Yes, I believe that's correct. If there were two genomes with the same species taxonomy, they got different `sp` numbers. I'm not positive though- feel free to reach out to Clare (the first author of the paper) - clare.lou@berkeley.edu

**Comment by Biofarmer** [comment]
Hi Matt, many thanks, Best, Wang

**Comment by Biofarmer** [comment]
Hi Matt,

I just have a question about the output of genomeWide_compare.tsv and strain_clusters.tsv? For one genome comparison from two samples, in the genomeWide_compare.tsv, the popANI is 0.999997 and percent_compared is 0.4. If based on suggested ≥99.999% popANI and ≥50% percent_genome_compared, the strains in these two samples are not same. However, in the strain_clusters.tsv, the strains from these two samples are clustered with same ID, meaning they are same strains. I think this difference is from COVERAGE_TRESHOLD for clustering, right? If so, which results should I take, results from strain_clusters.tsv?

Many thanks
Wang

**Comment by MrOlm** [comment]
Hi Wang,

By default `COVERAGE_TRESHOLD` is set to 0.1. So if you didn't change it, that's why these are the same strain. Another thing to keep in mind, though, is that the hierarchical clustering done is imperfect- see https://drep.readthedocs.io/en/latest/choosing_parameters.html#oddities-of-hierarchical-clustering (the same basic heriarchical methods used for dRep clustering are used in inStrian for clustering strains).

In my own opinion, the two organisms you describe are the same strain. The threshold used for `percent_genome_compared` really depends on your tolerance for False Positives (calling things the same that are actually different) and False Negatives (calling things different that are actually the same). Having a lower `percent_genome_compared` (like 0.1) will lead to more False Positives and less False Negatives. Have a higher percent_genome_compared (like 0.5) will lead to more False Negatives and less False Positives.

In my own studies, I think that a value of 0.1 or 0.3 is a good balance, and still very stringent (still a very small amount of False Positives). In Clare's bioRxiv she was very concerned about having absolutely no False Positives, so she increased it to 0.5. 

Best,
Matt

**Comment by Biofarmer** [comment]
Hi Matt,

Thanks for your always detailed reply, and it is very useful.

Best,
Wang

**Comment by MrOlm** [comment]
Hi Wang,

Yes, you're correct that it doesn't matter for dRep (as long as all of the scaffold names within a bin are unique), but for inStrain each scaffold name does need to be unique. One option is just to append the genome name to the scaffold name (k119_10 becomes genomeX_k119_10)

-Matt

**Comment by Biofarmer** [comment]
Hi Matt,

Thanks, it is good news for me. I just checked the scaffold names from the single concentrated genome, which turned out to be unique. The assembler I used for inStrain is SPAdes, so the format of scaffold name is >NODE_103_length_15567_cov_6.874742; together with UHGG genomes (scaffold name format is >GUT_GENOME214656_1) to make the genome database. I just want to confirm with you that inStrain will take all the content following '>' as the scaffold name, not taking part of it, right? If so, I then can ensure that unique scaffold name in single concentrated genome is applied to inStrain.

It's great to learn all the time.
Best, 
Wang

**Comment by MrOlm** [comment]
Hello,

Yes, that's correct. It uses everything after the `>` and stopping at the first whitespace (` `)

Best,
Matt

**Comment by Biofarmer** [comment]
Hi Matt, it's great that I don't need to re-run inStrain and safe for subsequent analysis. Best, Wang

**Comment by Biofarmer** [comment]
Hi Matt,

Just out of curiosity, is there any error or fail to run inStrain if the scaffold names are not unique in the single concentrated genome? 

Thanks
Wang

**Comment by MrOlm** [comment]
Honestly I'm not sure- I've never tried it

**Comment by Biofarmer** [comment]
Hi Matt, Okay, no problem. Best, Wang
