### ISSUE TITLE
instrain compare: dynamic output

### ISSUE THREAD

**Issue by nick-youngblut** [MrOlm/inStrain#54]
Running `instrain compare` in a snakemake kept failing for certain jobs. I realized that `instrain compare` will compress the output table if it is of a certain size:

```
        if store:
            out_base = self.get_output_base()
            ft = '.tsv'

            # If this file is going to be huge, compress it
            if len(db) > 1e6:
                ft = '.tsv.gz'
```

Can you please remove this dynamic output (ie., always `*.tsv` or `*.tsv.gz`)? It makes integrating `instrain` into a snakemake pipeline much more complicated.

**Comment by MrOlm** [comment]
I've added the option ``--force_compress`` to always compress the output in version 1.5.3

**Comment by nick-youngblut** [comment]
Thanks for implementing the change so quickly!
