### ISSUE TITLE
allele frequency 

### ISSUE THREAD

**Issue by Thexiyang** [MrOlm/inStrain#58]
Thanks for the very nice tool! In the output, there is no parameter for allele frequency. Is there any way to calculate this based on the output data? Thanks!

**Comment by MrOlm** [comment]
Hello,

In the file `SNVs.tsv` it lists the allele frequencies of the consensus, variant, and reference bases (https://instrain.readthedocs.io/en/latest/example_output.html#snvs-tsv)

Is there something else you're looking for, or is this it?

Best,
Matt

**Comment by Thexiyang** [comment]
Thanks. So does it mean that major allele frequency is equal to con_freq? Or should I only consider con_freq with the class label of SNV (not SNS)?

**Comment by MrOlm** [comment]
Con_freq is always the major allele frequency, and Var_freq is always the minor allele frequency. With the class label SNS, it means that only one allele was detected at a statistically significant level, but the frequency values are still accurate.

Best,
Matt

**Comment by Thexiyang** [comment]
Thanks. One more question. Where can I find the Fst? Or should I calculate it myself? Using this script: https://github.com/alexcritschristoph/soil_popgen/blob/master/inStrain_lite/inStrain_lite/fst.py? Could you provide some guidance?

**Comment by MrOlm** [comment]
Fst calculation isn’t officially supported in inStrain yet, but youre correct that that script provides a hacky way to do it. @alexcritschristoph wrote the script and may have more instructions

**Comment by MrOlm** [comment]
Hi Hugo- thanks for the comment. I thought I did something about that, but maybe I just intended to and didn't follow though. Can you confirm what version of inStrain you're running?

Thanks
Matt

**Comment by hdore** [comment]
Hi Matt, I'm running version v1.5.4.

**Comment by haihao999** [comment]
Hi，Matt
  I use the alexcritschristoph's script to calculate Fst, but I have a question about how to adjust the SNV calculation with inStrain for two populations with large differences in sequencing coverage.
Thanks,
yanpeng

**Comment by MrOlm** [comment]
Hey @alexcritschristoph - any idea about the answer to @haihao999 's question?

**Comment by haihao999** [comment]
Hi, Matt
If higher coverage is due to the higher sequencing depth at some samples, can I use samtools rmdup to process my BAM file? Will this processing have an impact on the results of InStrain?

**Comment by MrOlm** [comment]
Hello,

I'm not sure about the `samtools rmdup` command, but subsetting reads in the .bam file to create even coverage is a great idea that will work well.

-Matt
