### ISSUE TITLE
Question: extract haplotypes

### ISSUE THREAD

**Issue by Sebastien-Raguideau** [MrOlm/inStrain#61]
Hello,
I would like to extract haplotype in each of my samples. Can I just mine the SNVs.tsv file and extract 2 haplotype, the one constituted with con_base and var_base? How do you advise to proceed?
Best,
Seb

**Comment by MrOlm** [comment]
Hi Seb,

Phasing out haplotypes based on SNV frequencies is more difficult than meets that eye. Doing so usually requires complex computational algorithms. I am considering adding functionality to do this using the program Octopus (https://github.com/luntergroup/octopus/issues/156), but that's in early stages and I wouldn't expect this feature to be added any time soon. My advice would be to parse the output of SNVs.tsv and use it as an input to a halplotype phasing algorithm like Octopus.

I'll also note that if you do this and get it to work, I'd appreciate it if you'd be willing to share how you did it (I've never done this before).

Best,
Matt

**Comment by Sebastien-Raguideau** [comment]
Hi Mat,
Thanks for the super fast answer. 
I am actually in the process of comparing different haplotype phaser and I was under the misconception that inStrain was somehow implicitly outputting haplotypes. Interestingly I completely missed octopus as a potential tool. Other tools I'm considering are Desman (https://github.com/chrisquince/DESMAN), mixtureS (http://www.cs.ucf.edu/~xiaoman/mixtureS/) and strainfinder (https://github.com/marcomeola/StrainFinder). 
I think the most compatible one is DESMAN as it takes just snv positions/counts as input which is a good match to inStrain output. 
I may have a go in not too long and share method/results with you.
Best,
Seb

**Comment by MrOlm** [comment]
OK great! You hit all of the ones I'm aware of as well, but I haven't personally tried any of them. Interested to hear what you find!

-Matt
