### ISSUE TITLE
Script exiting at start of Step 2. Profile scaffolds

### ISSUE THREAD

**Issue by jmartin77777** [MrOlm/inStrain#66]
I'm trying to run inStrain on a collection of samples mapped against the UHGG database downloaded from the location mentioned in your tutorial #2.  And I'm using the docker container (mattolm/instrain:latest - as of 5/7/21 - log.log says its running v1.4.0).  I mapped my samples using bowtie2 v2.3.5.1 against UGHH_reps.fasta.bt2 (downloaded from tutorial link) and then launched instrain profile with these arguments:

inStrain profile -o <OUTPUT> -p 8 -g UHGG_reps.genes.fna -s UHGG_reps.stb --database_mode <SORTED_BAM> UHGG_reps.fasta

Step 1. Filter reads seems to work OK, giving this summary:

Scaffold to bin was made using .stb file
4371 of 4644 genomes have less than 1x estimated coverage
647207 of the original 679785 scaffolds are removed (647207 have a low coverage genome; 0 have no genome)
1.2% of reads were removed during filtering
29,678,358 read pairs remain (8.933 Gbp)

Then it prints the line:

***************************************************
.:: inStrain profile Step 2. Profile scaffolds ::..
***************************************************

and then exits.   The log.log files are rather large (~100Mb), but I'd be happy to compress & attach one here if that is helpful.   

I also noticed while searching this forum for similar issues that I think you mentioned a version 1.5.3, which I guess would be newer than whats available in your docker image.   Should I not be using that docker image?

**Comment by MrOlm** [comment]
Hello,

A couple of things. 1) When I use the Docker image, I just run `pip install instrain --upgrade` before doing anything else. The updates inStrian within the Docker image. 2) There are no more lines at all after `.:: inStrain profile Step 2. Profile scaffolds ::..`? No traceback or anything? 3) Could you please just paste in the last ~50 lines or so of the log file? 

Thanks,
Matt

**Comment by jmartin77777** [comment]
Ah, sorry, when I said nothing past the 'Step 2. Profiling scaffolds' I was talking about the STDOUT being captured by our job management software (LSF).  The log.log does have lots of debug info.   I've attached the last 50 lines of log.log for one of my samples (which is typical for all the samples)
[log.log.last50lines.txt](https://github.com/MrOlm/inStrain/files/6468799/log.log.last50lines.txt)

**Comment by MrOlm** [comment]
OK interesting- is it possible that it's running out of RAM? It looks like it's crashing right when it's loading the genes table, which can be kind of big when working with a large database like UHGG

**Comment by jmartin77777** [comment]
I can definitely allocate a great deal more memory, the jobs I launched were working with 30Gb.  My mapping files have ~20-40 million fragments each (filesizes ~3-6Gb).  I wasn't sure how much memory would be needed.

I will try 128Gb and I'll run instrain --upgrade first and see if that gets these working.

**Comment by MrOlm** [comment]
OK yes-  30Gb is probably not enough for that big of files. 128 should do it. Let me know if you hit more problems!

-Matt

**Comment by jmartin77777** [comment]
Allocating 128Gb memory, and updating to v1.5.3 did work.  Thanks for the help!

**Comment by MrOlm** [comment]
Great thanks for letting me know!
