### ISSUE TITLE
more filtered reads than raw reads?

### ISSUE THREAD

**Issue by rebeccasophiasalcedo** [MrOlm/inStrain#70]
Hi!

In the mapping_info.tsv file it says that there are more read pairs that passed all filtering steps than there were raw read pairs. Here is the whole tsv file. 
<img width="661" alt="Screen Shot 2021-06-03 at 4 10 13 PM" src="https://user-images.githubusercontent.com/78378647/120723218-2e840d80-c486-11eb-90a9-a3ce8db1f471.png">
<img width="1079" alt="Screen Shot 2021-06-03 at 4 10 35 PM" src="https://user-images.githubusercontent.com/78378647/120723249-3c399300-c486-11eb-9622-a942c28acccc.png">

At first I thought it was due to multi-mapped reads but it happened even when I set the min_mapq filter to >2 like you suggest in the important concepts page. In the output it even says that only 1,145,875 pairs remain after filtering but the tsv says 1,152,856 pairs.  

<img width="518" alt="Screen Shot 2021-06-03 at 4 15 10 PM" src="https://user-images.githubusercontent.com/78378647/120723584-e0bbd500-c486-11eb-9857-9d004bdac878.png">

I'm wondering if maybe the filtered_pairs column is actually filtered individual reads? Or did I interpret the table wrong?

here is the command I ran
inStrain profile  ../bam_files/SRR9001935_mapped_to_Nisl3F_edit_min70%aln.sorted.bam ../reference_genomes/Nisl3F/N.islandicus_genome_unwrapped.fna -o SRR9001935_instrain_min_mapq -g ../reference_genomes/Nisl3F/Nisl3F_prodigal_genes.fna -c 5 -l 0.94 --pairing_filter all_reads --min_mapq 2

Thanks you!

Rebecca

**Comment by MrOlm** [comment]
Hi Rebecca,

Thanks for reaching out. I think what's going on is confusion based on the confusing way that the data is presented in the mapping_info.tsv file, so apologies for that.

By my read of the data and .tsv, it's correct that 1,145,875 pairs remain. Where are you getting the 1,152,856 number from?

-Matt

**Comment by rebeccasophiasalcedo** [comment]
Whoops sorry! That's number is from an older run. But here it says that 1,145,875 pairs remain after filtering but there were 1,078,546 unfiltered pairs, so its still higher. 

-Rebecca

**Comment by MrOlm** [comment]
OK apologies- I see what's going on. This comes down to the funny way that inStrains handles the pairing_filter. A singleton read that passes the filters will be considered a "pair" and tallied in the "filtered_pairs" column.

Reads that are part of a pair have the same "name", with a .1 or .2 added to them depending on if they're the left or right read. The column "filtered_pairs" actually reports the number of read "name"s that pass filters. So a singleton read will add 1 to this tally, and a complete pair of reads will add 1 to this tally.

Let me know if that makes sense of if you still have questions.

-Matt

**Comment by rebeccasophiasalcedo** [comment]
ah okay! That makes sense. So the true number of filtered_pairs would be filtered_pairs_filtered singletons?

**Comment by MrOlm** [comment]
Yeah exactly (filtered_pairs - filtered singletons).

However, something that _might_ also be happening is double counting of discordant pairs. That is, if two ends of a pair align to different scaffolds, each end _might_ be counted in the `filtered_pairs` column (so a discordant pair might count in that column twice). But I'm not sure; discordant pairs are difficult to handle with the way inStrain is written and I forget the implementation details.

I will try and look through the code and add some documentation to this effect sometime soon, describing how those columns are impacted by changing the pairing filter. I won't have time to this this immediately though, so feel free to reach out if you have more questions.

-MO

**Comment by rebeccasophiasalcedo** [comment]
Okay good to know, that shouldn't be a problem for this project since I only have one scaffold but its good to keep in mind the the future. Thank you again!

**Comment by MrOlm** [comment]
I adjusting the reporting of this to be correct in inStrain v1.5.7
