### ISSUE TITLE
Issue with Single End Reads

### ISSUE THREAD

**Issue by rusher321** [MrOlm/inStrain#72]
Dear all: 
I know inStrain used the paired reads information when calling snp. 
Now, I have some single-end metagenome samples, want to how to perform inStrain to handle them? 

Thanks in advance ~

**Comment by MrOlm** [comment]
Hello,

To run single-end metagenomes simply add the flag `--pairing_filter non_discordant` to your inStrain profile command. Note that when you do this, each read will be considered a "pair" in the inStrain output (for example the `mapping_info.tsv` file.)

Let me know if you hit any snags.
-MO
