### ISSUE TITLE
inStrain compare result questions

### ISSUE THREAD

**Issue by jmartin77777** [MrOlm/inStrain#74]
I have a couple questions regarding the output of inStrain compare.  This is the same result you recently helped me understand the dendrogram for, 128 MGS samples that are 64 mother-child pairs.  One of our goals is looking at the heritability of strains from mother to child clustered according to various metadata we have.  The genome database we used is the 4644 genomes from the UHGG (one of the suggested, publicly available dbs described in your tutorial).  My questions are:

1- Is it surprising that it is very rare to see multiple strains of a reference genome appearing in a single sample? I am basing this statement from looking at the strain_clusters.tsv output

2- inStrain compare has zoomed in on 385 genomes out of the set of 4644 reference genomes in the UHGG.  I believe this is because these are the only genomes with strains appearing in >1 sample, but I haven't found anywhere that explicitly states that. Is that assumption correct?

Sorry for the basic questions, this tool has provided a great wealth of results and before getting too excited I want to be sure I understand what I'm working with!

**Comment by MrOlm** [comment]
Hello,

1) Based on the way that the inStrain algorithm works, each sample can only have a single strain per reference genome. InStrain does comparisons in a pairwise per-genome level, so for each genome that's compared between samples, a single popANI value is calculated. InStrain calls strains based on the distance matrix of popANI values generated for that genome using hierarchical clustering. In doing so, for each genome, each sample is assigned as a "strain". 

Hierarchical clustering can also introduce some weird results with edge cases, as described here - https://drep.readthedocs.io/en/latest/choosing_parameters.html#oddities-of-hierarchical-clustering

Let me know if this doesn't makes sense.

2) Assuming you ran inStrain compare with `--database_mode`, yes that's what's going on. Strain presence in a sample is calculated based on the `--breadth` flag, which by default is based on a breadth_minCov of 0.5. Only genome that are present in at least two samples are included. Apologizes for lacking documentation about this functionality.

Let me know if you run into any other snags or have another other questions

-MO
