### ISSUE TITLE
Fails after filtering reads: no paired reads

### ISSUE THREAD

**Issue by rebeccasophiasalcedo** [MrOlm/inStrain#76]
Hello! (it's me again)

I keep getting this error (Exception: No paired reads detected; see above message and log) when I try to run inStrain profile on any bam file. I've tried a couple of different bam files, including one's I've run on inStrain before, but they all end in the same error. I tried updating the software with pip and tried all iterations of --pairing_filter and --use_full_fasta_header, but it didn't seem to work.  Here's the output, the head of my sam file, the flagstat output from samtools on my sam file I feed to inStrain, the log and raw_data folder from the instrain output. All the bam's are recruited to the same reference genome so it could be my files, but I can't figure out what's wrong.  

<img width="854" alt="Screen Shot 2021-07-08 at 11 57 45 PM" src="https://user-images.githubusercontent.com/78378647/125036832-4b44cf80-e048-11eb-94c0-cd08bd259f68.png">
<img width="648" alt="Screen Shot 2021-07-08 at 11 45 55 PM" src="https://user-images.githubusercontent.com/78378647/125035691-f9e81080-e046-11eb-9657-dc14147897f1.png">
<img width="888" alt="Screen Shot 2021-07-08 at 11 32 38 PM" src="https://user-images.githubusercontent.com/78378647/125035699-fd7b9780-e046-11eb-955a-048e07b86aaa.png">
<img width="1108" alt="Screen Shot 2021-07-08 at 11 24 36 PM" src="https://user-images.githubusercontent.com/78378647/125035701-fe142e00-e046-11eb-8433-55037b853378.png">
<img width="1089" alt="Screen Shot 2021-07-08 at 11 49 08 PM" src="https://user-images.githubusercontent.com/78378647/125035809-1c7a2980-e047-11eb-9fbb-8f6c6868c73a.png">

Any advice would be extremely helpful!
Rebecca

**Comment by MrOlm** [comment]
Hi Rebecca,

Sorry you're having this problem. I'd love to fix it, but it's going to be really hard for me to troubleshoot without having access to the files. 

Would you be comfortable sending them to me? I'll need the .fasta file that you're using and the .sam file / .bam file. You could subset the .sam file using a tool like samtools to make it smaller and easier to send. If you are comfortable sharing, feel free to email me at mattolm@stanford.edu instead of uploading the files here.

Thanks,
MO

**Comment by MrOlm** [comment]
Looking at this some more I think I found the problem actually!

It looks like the problem may be a mismatch between the contig names in your .fasta file and the contig names in your .bam file. Can you confirm that you're providing the same .fasta file to inStrain that you use to map reads against? It looks like your .fasta file has just 1 contig, `GBSFallcontigs`, but that your .bam file doesn't show any reads mapped to that contig.

Using a tool like idxstats should tell you what contig names are in your .bam file, which could be helpful to figuring out how / why there's a mismatch (https://www.biostars.org/p/98854/)

Best,
Matt

**Comment by rebeccasophiasalcedo** [comment]
Ah, you're totally right! there was a typo in my fasta header, apologies. Thank you! And feel free to delete this issue since it wasnt related to the program :)

Best,
Rebecca

**Comment by MrOlm** [comment]
Glad this issue could be resolved!

-MO
