### ISSUE TITLE
Getting high number of SNS in reads that I used for Generation of SRGs

### ISSUE THREAD

**Issue by DDavila10** [MrOlm/inStrain#77]
Hi all,

I am using inStrain to analysis gut microbiome data. I created a SGRs by assembly, polishing and binning paired reads from one single sample. After mapping the same reads that I used for the generation of SGRs to the SGRs and running inStrain profile, I realized that some bins contains high count of SNS. If I understood correctly, SNS are sites with a fixed subtitution, meaning that all reads (100% reads mapped to a bin) contain a different allele than the reference genome. 

I was expecting that all bins contain 0 SNS because I used the same paired reads for generation of the SGRs. I would like to ask you if you have any idea why this is happening, if I need to change mapping parameters for generation of the .bam file or inStrain profile parameters or if is something expected and I misunderstood the meaning of SNS.

Thank you for your help and time!

Best,
Daniel Davila

**Comment by MrOlm** [comment]
Hi Daniel,

This is interesting- thanks for reaching out! I'm also surprised by this. I would expect very few SNSs when mapping reads back to bins that came from the assembly. I guess the only two explanations are that inStrain is incorrectly reporting SNSs or that the assembler is making some mistakes when assembling the genome. 

To figure out between the two I think it would be helpful to visualize the .bam file, seeing what the reads look like at some of the positions where inStrain is calling SNSs, and determining if inStrain or the reference genome is wrong. I would do this with the same .bam file used to run inStrain. Any mapping visualization program will do, but I've had good experiences with IGV (https://igv.org/app/). You can see the `SNV.tsv` file in the output to see the locations of what inStrain is calling SNSs. I'd also appreciate if it you let me know what you find.

Thanks,
Matt

**Comment by DDavila10** [comment]
Hi Matt,

Thank you for the support and help. I checked the .bam file using IGV and observed that all the reads mapped to the SNS position are the same (eg. 100% T) and differ from the reference genome base at that site (eg. A). So I guess is a mistake during assembling the reference genome. Do you have a guess on the best way to solve this issue?

Thanks again for your valuable help!

Best,
Daniel

**Comment by MrOlm** [comment]
Hi Daniel,

Thanks for following up! Interesting that the assembler is making these mistakes. I know there are tools that can polish assemblies using an assembly and bam file (one I'm aware of is Pilon), but I don't have experience running them myself. That could be a way of fixing the problems. Another option would be to use a different assembly algorithm.

Best,
Matt

**Comment by DDavila10** [comment]
Hi Matt, 

Thanks a lot for the suggestion! I will try them!

Best,
Daniel
