### ISSUE TITLE
inStrain compare assertion error: You're comparing ISP profiles that have the same names.

### ISSUE THREAD

**Issue by zhaoc1** [MrOlm/inStrain#79]
Hi,

I am trying inStrain out with the three samples used to generate Fig2c in the paper.

After running the profile for each sample with the default parameter, I tried 

```
inStrain compare -i instain_output/SRR12324252/ instain_output/SRR12324253/ -o test --stb repgenomes.stb --genome Bacillus_subtilis_complete_genome
```

And the error message I got is: 
`AssertionError: You're comparing ISP profiles that have the same names. No no.`

I am not sure what does this error message mean, and how to debug from here. 

Thank you!
Chunyu

**Comment by MrOlm** [comment]
Hi Chunyu,

Interesting- inStrain thinks that `instain_output/SRR12324252/` and `instain_output/SRR12324253/` have the same name, which doesn't seem to be the case.

To help debug, could you please send be the file `raw_data/attributes.tsv` within each of the `instrain_output` folders that you're comparing in the above command?

Thanks,
Matt

**Comment by zhaoc1** [comment]
Hi Matt,

Thanks for fast reply. Attached are the two `attributes.tsv` for `SRR12324252` and `SRR12324253`.


[attributes_SRR12324253.tsv.csv](https://github.com/MrOlm/inStrain/files/6933483/attributes_SRR12324253.tsv.csv)
[attributes_SRR12324252.tsv.csv](https://github.com/MrOlm/inStrain/files/6933485/attributes_SRR12324252.tsv.csv)

Thank you!
Chunyu

**Comment by MrOlm** [comment]
Hi Chunyu,

OK- I see the problem. Both of the inStrain profile objects were built with .bam files that have the same basename (`/mnt/cz/20210426_instrain/fig2c/midas_output_prebuilt/SRR12324253/temp/snps/repgenomes.bam` and `/mnt/cz/20210426_instrain/fig2c/midas_output_prebuilt/SRR12324252/temp/snps/repgenomes.bam`). InStrain names the profiles based on the basename of the .bam file, so it thinks that these two profiles have the same name.

Thanks for posting this issue; in the next inStrain update I'll make this error much more clear.

For you to solve this problem you have two potential options. 1) You could rename the .bam file basenames to be different from one another and re-run inStrain profile. This will almost certainly work. 2) You could edit the `raw_data/attributes` file  of one of the profiles to make inStrain think it has a different name. You would edit the line that starts with `bam_loc`. I'm 80% sure this would work, but there's a chance this could introduce other bugs that I'm not thinking of at the moment.

Thanks again,
Matt

**Comment by zhaoc1** [comment]
Awesome! Thanks for the quick debugging! I will start with option (2).
