### ISSUE TITLE
Outputting genome consensus sequences

### ISSUE THREAD

**Issue by jasonarothman** [MrOlm/inStrain#84]
Hi Matt,
Amazing software that was easy to pick up and run with. No complaints!
Apologies if I missed this somewhere: I have a question, or maybe a future release suggestion if it's not currently implemented:

When running inStrain profile, is there an option or location in the raw data to obtain a consensus sequence of the genomes? I can do this with other software, but seeing as inStrain is probably building consensus genomes as part of the pipeline, it'd be very handy to have these available.

Thanks,
Jason

**Comment by MrOlm** [comment]
Hi Jason,

Thanks for the kind words! Unfortunately the consensus genome is not stored anywhere or ever actually calculated via inStrain (the SNP calling is done in a confusing why that never actually calculates a consensus). I'll consider adding it during the next update, but this likely won't be for some time.

Thanks again for the input
-Matt

**Comment by MrOlm** [comment]
Hi Jason- In looking through the many things I hope to do with inStrain, I just don't have time to make this a priority. I will add it to my private "To Do" list but am going to remove this issue, and I wouldn't expect this feature anytime soon.

Thanks again for the suggestion!
-Matt
