### ISSUE TITLE
"Exception: no paired reads detected", however our files contain paired reads

### ISSUE THREAD

**Issue by gabrieleghiotto** [MrOlm/inStrain#89]
Hi,

I am using your tool (version 1.3.11) to perform some analyses in my thesis project and it throws an unexpected error.

This is the command line I used to launch inStrain profile:
inStrain profile /data/gabriele/test_25ottobre/botwie/all_genomes_CSTR02a.bam /data/gabriele/test_25ottobre/genomes/all_genomes.faa -o ISSUE_TO_GITHUB.IS -p 50 -g /data/gabriele/test_25ottobre/botwie/all_genomes.fa.genes.fna -s /data/gabriele/test_25ottobre/botwie/scaffold_to_bin_file.stb

At the end of the read filtering step the program throws the following error: "Exception: no paired reads detected"
I have checked with samtools if the error was due to some irregularities in our input BAM, and verified that paired reads are actually present.
I was able to run inStrain profile by setting the option --pairing_filter to "non_discordant", and the program didn't filter any reads. However, this behaviour is strange, given that our input files do contain paired reads.
What could be causing this error? Please find attached the output that was printed to screen during execution and the results of samtools on our input bam file.
[instrain_error_log.txt](https://github.com/MrOlm/inStrain/files/7442888/instrain_error_log.txt)
[pairedreads_check.txt](https://github.com/MrOlm/inStrain/files/7442890/pairedreads_check.txt)

Thanks in advance!

**Comment by gabrieleghiotto** [comment]
Hi,
thanks for your response. The headers of the paired reads were indeed different. We tried with your test data and it worked fine.
Best,
Gabriele

**Comment by MrOlm** [comment]
Great glad you got it working!
