### ISSUE TITLE
long-running time of read filtering step with 200+ mags 

### ISSUE THREAD

**Issue by yanhui09** [MrOlm/inStrain#9]
Hi Matthew

Thanks for the brianliant tool for the de-novo based population analysis.

I followed the tutorial and had a bechmark of several mags under version 1.2.4. It worked fine.
But when I applied to a bigger set of dereplicated mags, it got stuck at the read-filtering step, running for several hours.   
Here is the std and log.log file
[std.txt](https://github.com/MrOlm/inStrain/files/4282805/std.txt)
[log.log](https://github.com/MrOlm/inStrain/files/4282814/log.log)

From the log.log, it didn't move for several hours since below.
**03-03 08:42 INFO     Making read report
03-03 08:43 DEBUG    running on all reads
03-03 08:54 DEBUG    running on individual scaffolds**

I am not sure whether it's still running but just slowly. Is there any ways to solve this issue or just speed up? From the top command, I can see instrain is still running but without utilize those defined threads at this step.

Best
Yan

**Comment by alexcritschristoph** [comment]
Hi Yan,
My solution to this is to just run a separate process for each MAG. We know that it can slow for a lot of MAGs at the same time, although @MrOlm has been putting in a lot of effort to speed that up.
Alex

**Comment by yanhui09** [comment]
Hi Alex
Thanks for your quick response. 
To make things more speficc and avoid misusing inStrain, I shall:
1.  do the alignment using alll the concatenated reference fastas to avoid the mis-mapping.
2.  run **inStrain profile** separately on each MAG.
3.  do **inStrain compare** for MAGs within or across samples.

I am a bit curious about **inStrain compare** and **inStrian genome_wide**. 
If I run **inStrain profile** separately on the MAGs within one sample and followed by **inStrain compare** on those generated IS objects, it shall give the same result as directly using **inStrain profile** on all MAGs within that sample. 
Is that right?

Yan

**Comment by alexcritschristoph** [comment]
Hi Yan,
I think that workflow is exactly right! Remember that to run compare you have to be comparing different samples mapped to the same reference profiled with the same FASTA.

And yes, for that second part I believe your understanding is correct. Hope this makes sense, sorry it is a bit confusing.
Alex

**Comment by yanhui09** [comment]
Hi Alex
Thanks a lot. It works.
Yan

**Comment by elizabethmcd** [comment]
Hi Alex and Yan, 
I have a similar problem where I am trying to profile ~70 MAGs and the initial read/scaffold profiling takes some time. Apologies if I'm missing something obvious, but it isn't immediately clear to me how you mapped to all the references combined and then ran the profiling step on each MAG separately. For each individual profiling job, did you just give it the contigs for a single bin and the entire BAM file from the mapping job?
Thanks,
Elizabeth

**Comment by alexcritschristoph** [comment]
Hi Elizabeth, 
Honestly we each do it a bit separately - 
I'd do as you described - make a mapping index from all 70 MAGs and map to them together - then setup 70 jobs, giving each job just the FASTA from each MAG in the BAM.
InStrain will always be able to take a FASTA that is a subset of the FASTA that the BAM was mapped to!

@MrOlm tends to just give each mapping job a lot of threads - inStrain is mostly multi-threaded on a per-scaffold level (so huge scaffolds can slow down 1 thread for a while). I have found that takes longer though.

Hope this makes sense!
Alex

**Comment by elizabethmcd** [comment]
Hi Alex, 
Thanks for the quick response! That makes sense, and I'll try your option - I'm on a shared cluster and can't hog all the compute resources at once. 
Best,
Elizabeth
