### ISSUE TITLE
Subsetting reads / minimum MAG quality thresholds

### ISSUE THREAD

**Issue by andrewjmc** [MrOlm/inStrain#90]
Hello,

Firstly, thanks for producing/sharing/documenting/supporting such an amazing tool. Having just come across your tool today, I have two broad questions about applications. I am looking for organisms which may trigger a paediatric disease (Kawasaki Disease) and we are conscious that we need to be looking not just a species level but at strain/gene level.

We have metagenomic data from over 200 paediatric pharyngeal swabs (~50/50 case-control split). Although depth is good (generally >135 million read pairs), majority of reads are host, such that bacterial depth is lower (median 17 million; lower in KD likely because of throat inflammation and excess of human DNA).

I have identified a few organisms with differential abundance by disease group, and would like to explore their microdiversity. To that end, I've applied PanPhlAn 3 with a custom pangenome comprising two species representative genomes, a closely related species and 17 MAGs with >50% completeness and low contamination.

Although pangenome-level diversity (e.g. gene presence/absence) is the most likely source of causal disease associations (i.e. toxin gene), it makes sense to also look at strain-level sequence diversity.

**Question 1**
I appreciate the need for competitive mapping, and therefore comprehensive, ideally sample-generated, curated reference genome databases. However, would it be mad to consider an alternative approach to reduce complexity of extracting (say) genus-specific reads (thanks, kraken), and mapping to a database of dereplicated genus specific reference genomes and whole-sample MAGs?

I get that I would be explicitly losing reads with high homology outside the genus (or reads containing sequence only from my sample MAGs, unless I regenerate a whole new kraken database including these). However, I already know that the coverage of a reference genome is good (95% with deepest sample, mean depth ~50).

Given that I have >200 samples and I can assume that the comparison step scales with the square of the number of samples, I imagine I would reduce computational time by restricting the number of genomes/genes in this way.

**Question 2**
If I go down the route of whole-sample-MAG (+/- reference) approach, what do you consider as "good enough" from checkm? With my per-sample assemblies (MEGAHIT) and metabat 2 metagenomes, I have 2820 MAGs with completeness >50% contam <10% and 648 >90% completeness <10% contam. With the more typical 5% contamination threshold, this falls to 603. I lack the time and experience to do the sort of detailed manual MAG refinement illustrated by authors of tools like an'vio!

At the 90/10 threshold, with sourmash based MAG IDs, I have over 50 genera represented (some MAGs only identified at higher levels, perhaps hybrids), and 120 distinct species (GTDB-based) - up to 22 MAGs per species, but most only 1 or 2.

At the more relaxed threshold (50/10) I have nearly 80 genera, and 225 species, with up to 75 MAGs per species.

Thanks so much for your advice,

Andrew

**Comment by MrOlm** [comment]
Hi Andrew,

Thanks for your interesting question and good luck on your project! There are certainly multiple ways of doing the analysis you've outlined, as you say, but I'm happy to give my two-cents on the matter.

In regards to Question 1 I don't think what you're describing is mad, but I personally wouldn't recommended it. As you say the downside to doing this is that you'll only get to analyze reads that map to that genus in the kraken database (which could make you loose the coolest reads). The only upside is that mapping reads to your genome set will be a little bit quicker, but I'm sure the process of running kraken, extracting reads, and mapping again will actually result in process that's slower on net.

You're right that the comparison step is going to be time-consuming, but having less *reads* won't change the complexity at all; running a sample will take about the same amount of time either way. When running the comparison step you can specify which genome(s) you want to compare; so even if you map to a large database, you can tell inStrain to only profile / compare certain genomes in the database.

In terms of Question 2, it really just depends on the questions you're going after. If I were in your shoes, I would just go with the MIMAG standards to simplify things (https://www.nature.com/articles/nbt.3893/tables/1). For pan genome analysis, where completeness / contamination matters a lot, I would only use high-quality genomes. From mapping analysis (like inStrain), where completeness / contamination isn't a big deal, I'd use medium-quality genomes and above. 

Hope that helps!

Best,
Matt
