### ISSUE TITLE
Estimating number of strains based on nucleotide diversity, pop ANI, number of SNVs

### ISSUE THREAD

**Issue by gabrieleghiotto** [MrOlm/inStrain#93]
Hi,
I am using inStrain in my thesis project: my primary focus is to understand if in similar communities, a change in conditions results in a shift in strain composition. In order to do so, first I need to acess the number of strains corresponding to each MAG. As far as I understand, the microdiversity of each MAG can be estimated through the metrics of nucl_diversity, pop_ANI and SNVs_count. However, it seems to me that these metrics do not allow to distinguish how the microdiversity is spread across strains; for example, could it be that the same value of microdiversity can result from a few strains very different from each other, as well as a lot of strains, each carrying a small number of SNVs?
And if so, is there any metric produced by inStrain that we can use to distinguish between these cases?

Thanks in advance

Best,
Gabriele

**Comment by MrOlm** [comment]
Hi Gabriele,

Yes, on a fundamental level inStrain has no ability to determine the discrete number of strains present within a genome in a sample. Conceptually inStrain operates on the idea of “strain clouds” more than distinct strains. Doing haplotype phasing is something we’ve considered, but the feature won’t be coming any time in the near future.

The primary way to differentiate between the two cases you discuss (lots of strains that are similar to each other vs. a few strains that are divergent from each other) would be to look at the site frequency spectra (a graph of SNV prevalences). Having lots of SNVs at the same frequency would suggest one strain; having SNVs at a wide range of frequencies would suggest multiple strains. It's worth noting that this information is what is typically used to determine the discrete number of strains present in most halplotype phasing algorithms. Another option could be looking into the linkage of SNVs across the genome (to see if the SNVs are present on the same vs. different reads), but for this to be practical you'd need pretty long reads and a high density of SNVs.

It's also worth mentioning that recombination can make haplotype phasing very difficult / impossible. Checking out the linkage decay plot to see if recombination is occurring might also be useful.

Good luck with your project!
-Matt
