### ISSUE TITLE
inStrain compare not printing strain_clusters.tsv

### ISSUE THREAD

**Issue by clb21565** [MrOlm/inStrain#95]
Hi there, thanks for the hard work on this tool, excited to try it out. 

I have been able to run inStrain start to finish and mostly get the expected output, however the strain_cluster.tsv file is not being produced in the compare output folder. 
Commands: 

inStrain profile -p 32 ${sample}.sorted.bam ${refgenome} -o ${sample}.o 
inStrain compare -p 32 -i *.o -o inStrain_comparer 
inStrain genome_wide -i inStrain_comparer 
inStrain plot -pl 10 -p 32 -i inStrain_comparer/

The log file doesn't show anything obvious as to why and the plot of the cluster gets made with inStrain plot. Just no tsv file. Sorry if I  missed something obvious!

**Comment by MrOlm** [comment]
Hi Connor,

Strange! Could you please confirm that you're running the most up-to-date version of inStrain, and if so, could you attach your log file for the `compare` command?

Thanks!
-Matt

**Comment by clb21565** [comment]
Thanks for the fast reply! It does seem I have the most recent version (1.5.5) - attached is the log file. 

[log.log](https://github.com/MrOlm/inStrain/files/7706707/log.log)

**Comment by MrOlm** [comment]
Hi Connor,

OK- it seems like you have to provide an `-s` argument (scaffold to bin) to `inStrain compare` for that file to be created. If all .bam files are mapped to one genome, you can just profile the .fasta file of that genome for `-s`. 

Sorry for the confusion and let me know if you have any questions.

-Matt

**Comment by clb21565** [comment]
Yep, this fixed it! thank you!
C
