### ISSUE TITLE
allele frequency

### ISSUE THREAD

**Issue by YongyiPeng** [MrOlm/inStrain#96]
Thanks for your nice tool!
I noticed that con_freq is the major allele frequency, and I wander if the outgroups (ancestral alleles) are taken into account in the calculation of con_freq, since the minor alleles in the population now are not necessarily the ancient alleles in the past.
I would really appreciate your help on this.

**Comment by MrOlm** [comment]
Hello,

Yes! Con_freq is calculated as [major allele read count / total read count] at a given position

-Matt

**Comment by YongyiPeng** [comment]
Thank you so much for the prompt and clear response!
